import { EVENTS } from '../events';
import { emit } from '../eventBus';
import { addTimelineEvent } from '../utils/timeline';
import { ERPError, ERPSuccess } from '../utils/errors';
import { generateUniqueId } from '../utils/idGenerator';

const buildNotification = (title, message, department, priority = 'Medium', referenceId = '') => ({
  id: generateUniqueId('NOT'),
  title,
  message,
  department,
  priority,
  date: new Date().toISOString().split('T')[0],
  read: false,
  referenceId
});

const buildAuditLog = (user, action, orderNo = '', remarks = '') => ({
  id: generateUniqueId('AUD'),
  user: user || 'System',
  action,
  orderNo,
  date: new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }),
  time: new Date().toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true }),
  remarks
});

export const orderOrchestrator = {
  addLead: (state, leadData, dispatch, currentUser) => {
    if (currentUser?.role !== 'Sales' && currentUser?.role !== 'Sales Executive' && currentUser?.role !== 'Super Admin') {
      return ERPError('Unauthorized: Only Sales role can register leads.', 'UNAUTHORIZED');
    }

    // A sample is truly requested only if the master toggle is on AND at least one product was enabled
    const enabledSampleItems = (leadData.sampleItems || []).filter(si => si.enabled);
    const hasSampleRequest = leadData.sampleRequired && enabledSampleItems.length > 0;

    const newLead = {
      id: Date.now() + Math.floor(Math.random() * 100),
      ...leadData,
      status: hasSampleRequest ? 'Sample Stage' : 'New',
      timeline: [
        { stage: 'Lead Created', text: 'Lead captured', date: new Date().toISOString().split('T')[0], timestamp: Date.now() }
      ]
    };

    dispatch({ type: 'ADD_LEAD', payload: newLead });
    
    const audit = buildAuditLog(currentUser?.name, 'Lead Created', '', `Lead registered for ${newLead.companyName}`);
    dispatch({ type: 'ADD_AUDIT_LOG', payload: audit });

    emit(EVENTS.LEAD_CREATED, newLead);

    // Only create sample entries if the user explicitly toggled samples on for specific products
    if (hasSampleRequest) {
      const baseId = (state.samples || []).length > 0 ? Math.max(...state.samples.map(s => s.id)) + 1 : 1;
      enabledSampleItems.forEach((si, idx) => {
        const newSample = {
          id: baseId + idx,
          leadId: newLead.id,
          leadName: newLead.companyName,
          product: si.productName || leadData.productInterested || 'Sample Prototype',
          quantity: si.quantity || 1,
          expectedDate: si.expectedDate || '',
          status: 'Pending',
          createdAt: new Date().toISOString().split('T')[0]
        };
        dispatch({ type: 'ADD_SAMPLE', payload: newSample });
        const sampleAudit = buildAuditLog(currentUser?.name, 'Sample Requested', '', `Requested sample: ${newSample.product} for ${newSample.leadName}`);
        dispatch({ type: 'ADD_AUDIT_LOG', payload: sampleAudit });
      });
    }

    return ERPSuccess(newLead);
  },

  requestSample: (state, sampleData, dispatch, currentUser) => {
    if (currentUser?.role !== 'Sales' && currentUser?.role !== 'Sales Executive' && currentUser?.role !== 'Super Admin') {
      return ERPError('Unauthorized: Only Sales role can request samples.', 'UNAUTHORIZED');
    }
    const nextId = (state.samples || []).length > 0 ? Math.max(...state.samples.map(s => s.id)) + 1 : 1;
    const newSample = {
      id: nextId,
      ...sampleData,
      status: 'Pending',
      createdAt: new Date().toISOString().split('T')[0]
    };

    dispatch({ type: 'ADD_SAMPLE', payload: newSample });
    
    const audit = buildAuditLog(currentUser?.name, 'Sample Requested', '', `Requested sample ${newSample.product} for ${newSample.leadName}`);
    dispatch({ type: 'ADD_AUDIT_LOG', payload: audit });

    emit(EVENTS.SAMPLE_REQUESTED, newSample);
    return ERPSuccess(newSample);
  },

  confirmOrder: (state, qtn, dispatch, currentUser) => {
    if (currentUser?.role !== 'Sales' && currentUser?.role !== 'Sales Executive' && currentUser?.role !== 'Super Admin') {
      return ERPError('Unauthorized: Only Sales role can confirm orders.', 'UNAUTHORIZED');
    }

    // Check if quotation is already converted
    const existingQtn = (state.quotations || []).find(q => q.id === qtn.id);
    if (existingQtn && existingQtn.status === 'Converted') {
      return ERPError('Conflict: This quotation has already been converted to an order.', 'CONFLICT');
    }

    const orderNo = generateUniqueId('ORD');
    
    // Test 4: Prevent duplicate order ID
    const ordersList = state.orders || [];
    if (ordersList.some(o => o.orderNo === orderNo)) {
      return ERPError('Conflict: Duplicate order ID generated by platform.', 'CONFLICT');
    }

    const resolvedSalesperson = (state.leads || []).find(l => l.companyName.toLowerCase() === qtn.customerName.toLowerCase())?.salesperson || currentUser?.name || 'Alex Carter';

    let initialOrder = {
      orderNo,
      customer: {
        id: generateUniqueId('CUST'),
        name: qtn.customerName
      },
      products: qtn.items,
      detailedItems: qtn.detailedItems || [
        { productName: qtn.items, code: 'P-GEN', quantity: qtn.quantity, unitPrice: qtn.price, discount: qtn.discount, tax: qtn.tax }
      ],
      quantity: qtn.quantity || 1,
      totalQty: qtn.quantity || 1,
      dispatchedQty: 0,
      status: 'Pending',
      salesStatus: 'Pending',
      productionStatus: 'Pending',
      plantHeadStatus: 'Pending',
      storeStatus: 'Pending',
      dispatchStatus: 'Pending',
      financeStatus: 'Pending',
      overallStage: 'Pending',
      salesperson: resolvedSalesperson,
      currentDepartment: 'Sales',
      isDelayed: false,
      timeline: [],
      dispatch: {
        total: qtn.quantity || 1,
        completed: 0,
        remaining: qtn.quantity || 1
      },
      payment: {
        totalAmount: qtn.totalAmount,
        paid: 0,
        outstanding: qtn.totalAmount
      },
      transportCharge: qtn.transportCharge || 0,
      createdAt: Date.now()
    };

    initialOrder = addTimelineEvent(initialOrder, 'Created', 'Purchase order created by Sales');

    const invoiceNo = generateUniqueId('INV');
    
    let days = 14;
    if (qtn.paymentTerms) {
      const match = qtn.paymentTerms.match(/(\d+)/);
      if (match) {
        days = parseInt(match[1], 10);
      }
    }

    const payment = {
      id: generateUniqueId('PAY'),
      orderNo,
      customerName: qtn.customerName,
      invoiceNo,
      totalAmount: qtn.totalAmount,
      paidAmount: 0,
      dueDate: new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      status: 'Outstanding',
      verified: 'None'
    };

    const customer = {
      id: initialOrder.customer.id,
      name: qtn.customerName,
      email: `${qtn.customerName.toLowerCase().replace(/[^a-z0-9]/g, '')}@contact.com`,
      phone: '+91 9876543' + Math.floor(10 + Math.random() * 89),
      totalOrders: 1,
      totalRevenue: 0,
      outstanding: qtn.totalAmount,
      address: 'Industrial Plot #42, Phase 3',
      ordersHistory: [{ orderNo, product: qtn.items, val: qtn.totalAmount }],
      communicationLogs: [{ date: new Date().toISOString().split('T')[0], type: 'System', summary: 'Customer created from quote confirm' }]
    };

    dispatch({
      type: 'CONFIRM_ORDER',
      payload: { order: initialOrder, payment, customer }
    });

    dispatch({
      type: 'UPDATE_QUOTATION',
      payload: { id: qtn.id, status: 'Converted' }
    });

    const notif = buildNotification(
      'New Order Confirmed',
      `Order ${orderNo} confirmed for ${qtn.customerName}. Production scheduled.`,
      'Production',
      'High',
      orderNo
    );
    dispatch({ type: 'ADD_NOTIFICATION', payload: notif });

    const audit = buildAuditLog(currentUser?.name, 'Order Confirmed', orderNo, `Purchase Order ${orderNo} confirmed from QTN-${qtn.id}`);
    dispatch({ type: 'ADD_AUDIT_LOG', payload: audit });

    dispatch({
      type: 'RECORD_EVENT',
      payload: {
        id: generateUniqueId('EVT'),
        entity: 'ORDER',
        entityId: orderNo,
        action: 'CREATED',
        payload: initialOrder,
        timestamp: Date.now(),
        user: currentUser?.name || 'System'
      }
    });

    emit(EVENTS.ORDER_CONFIRMED, initialOrder);
    return ERPSuccess({ orderNo, order: initialOrder });
  },

  createOrder: (state, orderData, dispatch, currentUser) => {
    if (currentUser?.role !== 'Sales' && currentUser?.role !== 'Sales Executive' && currentUser?.role !== 'Super Admin') {
      return ERPError('Unauthorized: Only Sales role can create orders.', 'UNAUTHORIZED');
    }

    const orderNo = generateUniqueId('ORD');
    
    // Prevent duplicate order ID
    const ordersList = state.orders || [];
    if (ordersList.some(o => o.orderNo === orderNo)) {
      return ERPError('Conflict: Duplicate order ID generated by platform.', 'CONFLICT');
    }

    const customerName = orderData.customerName;
    const products = orderData.productName;
    const quantity = Number(orderData.quantity);

    // Calc value
    const unitPrice = 15000; // Mock unit price
    const totalAmount = quantity * unitPrice;

    let initialOrder = {
      orderNo,
      customer: {
        id: generateUniqueId('CUST'),
        name: customerName
      },
      products,
      detailedItems: [
        { productName: products, code: 'P-GEN', quantity, unitPrice, discount: 0, tax: 18 }
      ],
      quantity,
      totalQty: quantity,
      status: 'Pending',
      salesStatus: 'Pending',
      productionStatus: 'Pending',
      plantHeadStatus: 'Pending',
      storeStatus: 'Pending',
      dispatchStatus: 'Pending',
      financeStatus: 'Pending',
      overallStage: 'Pending',
      salesperson: currentUser?.name || 'Alex Carter',
      currentDepartment: 'Sales',
      isDelayed: false, // Delay tracking default
      hasWorkOrder: false,
      timeline: [],
      dispatch: {
        total: quantity,
        completed: 0,
        remaining: quantity
      },
      payment: {
        totalAmount,
        paid: 0,
        outstanding: totalAmount
      },
      createdAt: Date.now()
    };

    initialOrder = addTimelineEvent(initialOrder, 'Created', 'Purchase order created directly by Sales');

    const invoiceNo = generateUniqueId('INV');
    const payment = {
      id: generateUniqueId('PAY'),
      orderNo,
      customerName,
      invoiceNo,
      totalAmount,
      paidAmount: 0,
      dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      status: 'Outstanding',
      verified: 'None'
    };

    const customer = {
      id: initialOrder.customer.id,
      name: customerName,
      email: `${customerName.toLowerCase().replace(/[^a-z0-9]/g, '')}@contact.com`,
      phone: '+91 9876543' + Math.floor(10 + Math.random() * 89),
      totalOrders: 1,
      totalRevenue: 0,
      outstanding: totalAmount,
      address: 'Industrial Plot #42, Phase 3',
      ordersHistory: [{ orderNo, product: products, val: totalAmount }],
      communicationLogs: [{ date: new Date().toISOString().split('T')[0], type: 'System', summary: 'Customer created from direct order' }]
    };

    dispatch({
      type: 'CONFIRM_ORDER',
      payload: { order: initialOrder, payment, customer }
    });

    const notif = {
      id: generateUniqueId('NOT'),
      title: 'New Order Confirmed',
      message: `Order ${orderNo} created directly by Sales for ${customerName}. Target date planning required.`,
      department: 'Plant Head',
      priority: 'High',
      date: new Date().toISOString().split('T')[0],
      read: false,
      referenceId: orderNo,
      type: 'ORDER_CREATED',
      target: 'Plant Head'
    };
    dispatch({ type: 'ADD_NOTIFICATION', payload: notif });

    const audit = buildAuditLog(currentUser?.name, 'Order Confirmed', orderNo, `Direct Purchase Order ${orderNo} created`);
    dispatch({ type: 'ADD_AUDIT_LOG', payload: audit });

    dispatch({
      type: 'RECORD_EVENT',
      payload: {
        id: generateUniqueId('EVT'),
        entity: 'ORDER',
        entityId: orderNo,
        action: 'CREATED',
        payload: initialOrder,
        timestamp: Date.now(),
        user: currentUser?.name || 'System'
      }
    });

    emit(EVENTS.ORDER_CONFIRMED, initialOrder);
    return ERPSuccess({ orderNo, order: initialOrder });
  }
};
