-- Additive vendor invoice/payment tables. Supplier is the canonical vendor master.
CREATE TABLE IF NOT EXISTS "VendorInvoice" ("id" TEXT PRIMARY KEY, "invoiceNumber" TEXT NOT NULL, "supplierId" TEXT NOT NULL REFERENCES "Supplier"("id"), "purchaseOrderId" TEXT NOT NULL REFERENCES "PurchaseOrder"("id"), "status" TEXT NOT NULL DEFAULT 'DRAFT', "invoiceDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dueDate" TIMESTAMP(3), "totalAmount" DECIMAL(14,2) NOT NULL, "paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0, "version" INTEGER NOT NULL DEFAULT 1, "matchResult" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "VendorInvoice_supplierId_invoiceNumber_key" ON "VendorInvoice"("supplierId", "invoiceNumber");
CREATE INDEX IF NOT EXISTS "VendorInvoice_status_dueDate_idx" ON "VendorInvoice"("status", "dueDate");
CREATE TABLE IF NOT EXISTS "VendorInvoiceItem" ("id" TEXT PRIMARY KEY, "vendorInvoiceId" TEXT NOT NULL REFERENCES "VendorInvoice"("id") ON DELETE CASCADE, "productId" TEXT NOT NULL REFERENCES "Product"("id"), "quantity" DECIMAL(14,2) NOT NULL, "unitRate" DECIMAL(14,2) NOT NULL, "gstPercent" DECIMAL(5,2) NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS "VendorPayment" ("id" TEXT PRIMARY KEY, "paymentNumber" TEXT NOT NULL, "supplierId" TEXT NOT NULL REFERENCES "Supplier"("id"), "status" TEXT NOT NULL DEFAULT 'DRAFT', "paymentDate" TIMESTAMP(3), "transactionId" TEXT, "paidAmount" DECIMAL(14,2) NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "VendorPayment_paymentNumber_key" ON "VendorPayment"("paymentNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "VendorPayment_transactionId_key" ON "VendorPayment"("transactionId");
CREATE TABLE IF NOT EXISTS "VendorPaymentAllocation" ("id" TEXT PRIMARY KEY, "vendorPaymentId" TEXT NOT NULL REFERENCES "VendorPayment"("id") ON DELETE CASCADE, "vendorInvoiceId" TEXT NOT NULL REFERENCES "VendorInvoice"("id"), "amount" DECIMAL(14,2) NOT NULL, UNIQUE("vendorPaymentId", "vendorInvoiceId"));
