const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// Authoritative 217 Master Raw Inventory Items (Self-contained, zero file dependencies)
const MASTER_RAW_MATERIALS = [
  {
    "code": "HM107",
    "name": "Sandpaper (Grit 400)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM106",
    "name": "Sandpaper (Grit 320)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM105",
    "name": "Sandpaper (Grit 220)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM104",
    "name": "Sandpaper (Grit 180)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM103",
    "name": "Sandpaper (Grit 120)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM102",
    "name": "Sandpaper (Grit 80)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM216",
    "name": "Hunndi",
    "category": "Raw Material",
    "unit": "Pcs",
    "currentStock": 100,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM215",
    "name": "iron hammer",
    "category": "Raw Material",
    "unit": "Pcs",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM214",
    "name": "c clamp 12",
    "category": "Raw Material",
    "unit": "Pcs",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM213",
    "name": "c clamp 4",
    "category": "Raw Material",
    "unit": "Pcs",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM212",
    "name": "golden brown pigment",
    "category": "Raw Material",
    "unit": "Kg",
    "currentStock": 3,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM211",
    "name": "TERRA COATA Pigment",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 12,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM210",
    "name": "BROWAN Pigment",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM209",
    "name": "FAVDE HANDLE",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM208",
    "name": "Thundor File",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM207",
    "name": "Flat File",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM206",
    "name": "Round File",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM205",
    "name": "Pliers (Pakkad)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM204",
    "name": "handle",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM203",
    "name": "bear disc 36",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 50,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM202",
    "name": "sending machine pad",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM201",
    "name": "welcro paper 600",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 50,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM200",
    "name": "welcro paper 400",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 40,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM199",
    "name": "welcro paper 320",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 45,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM198",
    "name": "welcro paper 220",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 15,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM197",
    "name": "welcro paper 180",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 28,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM196",
    "name": "welcro paper 120",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 60,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM195",
    "name": "welcro paper 80",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 75,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM194",
    "name": "bear disc 120",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 30,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM193",
    "name": "bear disc 80",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 70,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM192",
    "name": "RED BRICK PIGMENT",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 20,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM191",
    "name": "c clamp big",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM190",
    "name": "buffing machine",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM189",
    "name": "WELDING ROD",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 180,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM188",
    "name": "welcro paper 600 grit",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 50,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM187",
    "name": "bear disc 120",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 30,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM186-B",
    "name": "bear disc 80",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 70,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM186",
    "name": "sand paper 180",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 28,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM185",
    "name": "MEASURING TAPE",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM184",
    "name": "bucket 12no",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM183",
    "name": "BALTI MID",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM182",
    "name": "steel putty blade 5/6\"",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 30,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM181",
    "name": "steel putty blade 8\"",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM180",
    "name": "steel putty blade 50*150mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM179",
    "name": "p v",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM178",
    "name": "sterar 10mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 22,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM177",
    "name": "sterar 8mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM176",
    "name": "sand paper 600",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM175",
    "name": "emery paper 80",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1630,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM174",
    "name": "D A GREY",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 45,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM173",
    "name": "balti small 8 NO",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM172",
    "name": "NYLON BLOCK PATTI SMALL",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM171",
    "name": "dhaga",
    "category": "Raw Material",
    "unit": "BOX",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM170",
    "name": "rassi/plastic sulti",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM169",
    "name": "grey moja",
    "category": "Raw Material",
    "unit": "PAIR",
    "currentStock": 35,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM168",
    "name": "wire tape",
    "category": "Raw Material",
    "unit": "PKT",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM167",
    "name": "write angle",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM166",
    "name": "allen key",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM165",
    "name": "handle patra",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM164",
    "name": "pvc farsi white",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 42,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM163",
    "name": "Fawda",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM162",
    "name": "Ecodrive Belt",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM161",
    "name": "Acid Gloves",
    "category": "Raw Material",
    "unit": "SET",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM160",
    "name": "Reileas Chemicale",
    "category": "Raw Material",
    "unit": "BRL(200LTR)",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM159",
    "name": "Admixture CHEMICAL",
    "category": "Raw Material",
    "unit": "BRL'",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM158",
    "name": "Grees",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM157",
    "name": "Wire BUNDLE",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM156",
    "name": "Belcha",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 3,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM155",
    "name": "Cloth Gloves",
    "category": "Raw Material",
    "unit": "SET",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM154",
    "name": "fingure",
    "category": "Raw Material",
    "unit": "PKT",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM153",
    "name": "glinder paid wheel",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM152",
    "name": "iron cutter disc",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 75,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM151",
    "name": "patra",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM150",
    "name": "hydralic oil",
    "category": "Raw Material",
    "unit": "LTR",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM149",
    "name": "hamer",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 7,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM148",
    "name": "spaner kit",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM147",
    "name": "duble seel rubber 4mm",
    "category": "Raw Material",
    "unit": "METER",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM146",
    "name": "plug box",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM145",
    "name": "gogels",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM144",
    "name": "mask",
    "category": "Raw Material",
    "unit": "PKT",
    "currentStock": 310,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM143",
    "name": "yellow gloves",
    "category": "Raw Material",
    "unit": "SET",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM142",
    "name": "fevikick",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 40,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM141",
    "name": "hand mixture carbon",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 20,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM140",
    "name": "hand mixture sterer 8mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM139",
    "name": "hand mixture sterer 10mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM138",
    "name": "hand mixter",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM137",
    "name": "grinder carbon",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 60,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM136",
    "name": "blue colour",
    "category": "Raw Material",
    "unit": "CAN",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM135",
    "name": "black colour",
    "category": "Raw Material",
    "unit": "CAN",
    "currentStock": 12,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM134",
    "name": "grey colour",
    "category": "Raw Material",
    "unit": "CAN",
    "currentStock": 24,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM133",
    "name": "desil",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM132",
    "name": "jadu",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM131",
    "name": "knife blade frame",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM130",
    "name": "knife blade",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 120,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM129",
    "name": "packing role thread",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM128",
    "name": "raping White tape",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM127",
    "name": "stone bit",
    "category": "Raw Material",
    "unit": "PKT",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM126",
    "name": "raping role",
    "category": "Raw Material",
    "unit": "ROLL",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM125",
    "name": "masking tape",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 288,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM124",
    "name": "flap disc",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 30,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM123",
    "name": "cloth",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 3,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM122",
    "name": "c clamp",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM121",
    "name": "roundhandel",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM120",
    "name": "c handel",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM119",
    "name": "attandance sheet",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM118",
    "name": "NOTEBOOK",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM117",
    "name": "eraser",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 20,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM116",
    "name": "sharpner",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 10,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM115",
    "name": "pencile",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM114",
    "name": "board marker",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM113",
    "name": "permenent marker",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 15,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM112",
    "name": "pen",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM111",
    "name": "ply wood 18mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM110",
    "name": "ply wood 12mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM109",
    "name": "ply wood 6mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM108",
    "name": "Buffing/Polishing Compound (Paste Form)",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM101",
    "name": "Emery Paper (Grit 1200)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 8,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM100",
    "name": "Emery Paper (Grit 1000)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 340,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM099",
    "name": "Emery Paper (Grit 800)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 100,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM098",
    "name": "Emery Paper (Grit 600)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 140,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM097",
    "name": "Emery Paper (Grit 400)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 790,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM096",
    "name": "Emery Paper (Grit 320)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 300,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM095",
    "name": "Emery Paper (Grit 220)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 50,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM094",
    "name": "Emery Paper (Grit 150)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 800,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM093",
    "name": "Emery Paper (Grit 120)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 25,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM092",
    "name": "Emery Paper (Grit 60)",
    "category": "Raw Material",
    "unit": "ROLL",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM091",
    "name": "Hole Saw Cutter – 50mm Diameter",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM090",
    "name": "Hole Saw Cutter – 25mm Diameter",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM089",
    "name": "HSS Twist Drill Bit – 12mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 17,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM088",
    "name": "HSS Twist Drill Bit – 10mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 8,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM087",
    "name": "HSS Twist Drill Bit – 8mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM086",
    "name": "HSS Twist Drill Bit – 6mm *210mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 23,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM085",
    "name": "HSS Twist Drill Bit – 6mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 11,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM084",
    "name": "HSS Twist Drill Bit – 4mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 10,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM083",
    "name": "HSS Twist Drill Bit – 3mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 10,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM082",
    "name": "Masonry Drill Bit",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM081",
    "name": "Electric Drill Machine (Variable Speed)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM080",
    "name": "Plaster of Paris (CaSO₄·½H₂O)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 23,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM079",
    "name": "Surface Primer for FRP Application",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM078",
    "name": "buffing compond",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM077",
    "name": "Orbital/Eccentric Sanding Machine",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM076",
    "name": "Cotton Wool Buffing Pad",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM075",
    "name": "Electric Polishing Machine (Rotary/Orbital)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM074",
    "name": "spary gun nozzel 4mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM073",
    "name": "Air Spray Gun for Gel Coat/Primer Application",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM072",
    "name": "Digital Vernier Caliper (0.01 mm accuracy)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM071",
    "name": "grinder lock nut",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 20,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM070",
    "name": "bear disc 60",
    "category": "Raw Material",
    "unit": "PKT",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM069",
    "name": "gc wheel",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 65,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM068",
    "name": "dimanod cutter",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 60,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM067",
    "name": "Angle Grinder (4\"/5\")",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 8,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM066",
    "name": "wood cutter blade",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM065",
    "name": "Wood/Composite Router Machine",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM064",
    "name": "jigsaw blade",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 80,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM063",
    "name": "Electric Jigsaw Machine",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM062",
    "name": "head screwdriver small",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM061",
    "name": "head screwdriver big",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM060",
    "name": "General Purpose Chisel",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM059",
    "name": "Flat Chisel –50",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 45,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM058",
    "name": "Flat Chisel - 32",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 30,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM057",
    "name": "Flat Chisel -25",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 20,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM056",
    "name": "Flat Chisel –40",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 40,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM055",
    "name": "Steel Ruler / Engineer Scale small 2 feet",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM054",
    "name": "Steel Ruler / Engineer Scale small 1.5 feet",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 4,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM053",
    "name": "Steel Ruler / Engineer Scale Medium",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM052",
    "name": "Steel Measuring Tape (3m",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 7,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM051",
    "name": "Steel Measuring Tape (5m",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM050",
    "name": "Hacksaw Blade",
    "category": "Raw Material",
    "unit": "NOS",
    "currentStock": 340,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM049",
    "name": "Steel Putty blade (2\")",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 60,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM048",
    "name": "Steel Putty blade (4\")",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 13,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM047",
    "name": "balti big 20",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 7,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM046",
    "name": "balti small 5 to 18",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM045",
    "name": "mugga big",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 11,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM044",
    "name": "mugga small",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM043",
    "name": "bucket 14no",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM042",
    "name": "bucket 19no",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM041",
    "name": "bucket 10no",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 24,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM040",
    "name": "bucket 12no",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM039",
    "name": "bucket 8no",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 8,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM038",
    "name": "thapi 12",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 3,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM037",
    "name": "thapi 10",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 14,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM036",
    "name": "thapi 8",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 54,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM035",
    "name": "thapi 6",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 56,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM034",
    "name": "thapi SMALL",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 45,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM033",
    "name": "Paint Brush 100mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 73,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM032",
    "name": "Brush 25mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 54,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM031",
    "name": "Paint Brush 75mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 310,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM030",
    "name": "Paint Brush 50mm",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 315,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM029",
    "name": "Thinner (General Purpose Paint/Resin Thinner)",
    "category": "Raw Material",
    "unit": "LTR",
    "currentStock": 450,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM028",
    "name": "Acetone (Solvent)",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM027",
    "name": "Gel Coat Grade Filler Powder",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 75,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM026",
    "name": "General Mineral Filler (e.g., Dolomite Powder)",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM025",
    "name": "Quartz Powder – black and white",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM024",
    "name": "Quartz Powder – big",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM023",
    "name": "Quartz Powder – medium",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM022",
    "name": "Quartz Powder – small",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM021",
    "name": "Dimethylaniline (DMA) Promoter",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM020",
    "name": "Cobalt Octoate Solution (Accelerator)",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 60,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM019",
    "name": "Methyl Ethyl Ketone Peroxide (Catalyst)",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 30,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM018",
    "name": "Unidirectional Fiberglass Mat – 1230 GSM",
    "category": "Raw Material",
    "unit": "ROLL",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM017",
    "name": "Woven Roving – 610 GSM",
    "category": "Raw Material",
    "unit": "ROLL",
    "currentStock": 65,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM016",
    "name": "Chopped Strand Mat – 450 GSM",
    "category": "Raw Material",
    "unit": "ROLL",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM015",
    "name": "Chopped Strand Mat – 225 GSM",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 99,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM014",
    "name": "Surface Tissue Mat (30 GSM)",
    "category": "Raw Material",
    "unit": "ROLL",
    "currentStock": 1,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM013",
    "name": "Isophthalic Gel Coat (Pre-accelerated)",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM012",
    "name": "Vinyl Ester Resin",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM011",
    "name": "Isophthalic Polyester Resin",
    "category": "Raw Material",
    "unit": "KGS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM010",
    "name": "General Purpose Unsaturated Polyester Resin (Clear)",
    "category": "Raw Material",
    "unit": "BAREL",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM009",
    "name": "Polyethylene Terephthalate Resin (PET)",
    "category": "Raw Material",
    "unit": "BAREL",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM008",
    "name": "Phthalocyanine Blue Pigment",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM007",
    "name": "Black Pigment",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 8,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM006",
    "name": "LIGHT GREY PIGMENT",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM005",
    "name": "White Pigment (TiO₂)",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 9,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM004",
    "name": "NC-50 Solvent-Based Mold Release Agent",
    "category": "Raw Material",
    "unit": "PCS",
    "currentStock": 0,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "OUT OF STOCK",
    "fsnVelocity": "Non-Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM003",
    "name": "Polyvinyl Alcohol (PVA) Release Agent",
    "category": "Raw Material",
    "unit": "LTR",
    "currentStock": 20,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM002",
    "name": "Benjo Mold Release Wax Polish",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 2,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Slow Moving",
    "storageLocation": "Raw Material Store"
  },
  {
    "code": "HM001",
    "name": "White Mold Release Wax Polish",
    "category": "Raw Material",
    "unit": "KG",
    "currentStock": 85,
    "minStock": 0,
    "reorderLevel": 0,
    "unitRate": 0,
    "totalStockValue": 0,
    "stockStatus": "IN STOCK",
    "fsnVelocity": "Fast Moving",
    "storageLocation": "Raw Material Store"
  }
];

async function main() {
  console.log('=== HIMALAYA ERP — VPS RAW INVENTORY SYNC ===');
  console.log(`Processing ${MASTER_RAW_MATERIALS.length} master raw materials...`);

  // Detect target company
  let company = await prisma.company.findFirst({
    where: {
      OR: [
        { id: '88c57ebc-b3b7-49e3-8d5d-6321a0e89015' },
        { users: { some: { email: { contains: 'himalayaerp.com' } } } }
      ]
    }
  });

  if (!company) {
    company = await prisma.company.findFirst();
  }

  if (!company) {
    throw new Error('No company found in database!');
  }

  console.log(`Using company: "${company.name}" (${company.id})`);

  let warehouse = await prisma.warehouse.findFirst({
    where: { companyId: company.id }
  });
  if (!warehouse) {
    warehouse = await prisma.warehouse.create({
      data: {
        companyId: company.id,
        name: 'Main Store'
      }
    });
  }
  console.log(`Using warehouse: "${warehouse.name}" (${warehouse.id})`);

  // Clear stale opening stock transactions
  await prisma.inventoryTransaction.deleteMany({
    where: {
      companyId: company.id,
      OR: [
        { referenceType: 'OPENING_STOCK' },
        { referenceId: 'INITIAL_SEED' },
        { referenceId: 'MASTER_INVENTORY_IMPORT' },
        { rawMaterialId: { not: null } }
      ]
    }
  });

  let rmUpserted = 0;
  let prodUpserted = 0;
  let txCreated = 0;
  let totalStock = 0;

  for (const item of MASTER_RAW_MATERIALS) {
    const publicId = `RM-${item.code}`;
    const prodPublicId = `PROD-${item.code}`;
    const cleanUnit = (item.unit || 'PCS').trim();

    // 1. Upsert RawMaterial
    let rm = await prisma.rawMaterial.findFirst({
      where: {
        OR: [
          { sku: item.code },
          { publicId }
        ]
      }
    });

    if (!rm) {
      rm = await prisma.rawMaterial.create({
        data: {
          publicId,
          companyId: company.id,
          sku: item.code,
          name: item.name,
          category: item.category,
          unit: cleanUnit,
          minimumStock: item.minStock,
          storageLocation: item.storageLocation,
          isActive: true,
        }
      });
    } else {
      rm = await prisma.rawMaterial.update({
        where: { id: rm.id },
        data: {
          companyId: company.id,
          name: item.name,
          sku: item.code,
          category: item.category,
          unit: cleanUnit,
          minimumStock: item.minStock,
          storageLocation: item.storageLocation,
          isActive: true,
        }
      });
    }
    rmUpserted++;

    // 2. Upsert Product
    let prod = await prisma.product.findFirst({
      where: {
        OR: [
          { sku: item.code },
          { publicId: prodPublicId },
          { id: rm.id }
        ]
      }
    });

    if (!prod) {
      const existingById = await prisma.product.findUnique({ where: { id: rm.id } });
      const createData = {
        publicId: prodPublicId,
        companyId: company.id,
        sku: item.code,
        name: item.name,
        category: item.category,
        productType: 'RAW_MATERIAL',
        unit: cleanUnit,
        unitPrice: item.unitRate,
        minimumStock: item.minStock,
        isActive: true,
      };
      if (!existingById) createData.id = rm.id;
      prod = await prisma.product.create({ data: createData });
    } else {
      prod = await prisma.product.update({
        where: { id: prod.id },
        data: {
          companyId: company.id,
          name: item.name,
          sku: item.code,
          category: item.category,
          productType: 'RAW_MATERIAL',
          unit: cleanUnit,
          unitPrice: item.unitRate,
          minimumStock: item.minStock,
          isActive: true,
        }
      });
    }
    prodUpserted++;

    // 3. Opening Stock Transaction
    if (item.currentStock > 0) {
      await prisma.inventoryTransaction.create({
        data: {
          companyId: company.id,
          rawMaterialId: rm.id,
          productId: prod.id,
          warehouseId: warehouse.id,
          type: 'OPENING_STOCK',
          quantity: item.currentStock,
          referenceType: 'OPENING_STOCK',
          referenceId: 'MASTER_INVENTORY_IMPORT',
        }
      });
      txCreated++;
      totalStock += item.currentStock;
    }
  }

  console.log('\n✅ SYNC COMPLETE:');
  console.log(`  - Raw Materials in Database: ${rmUpserted}`);
  console.log(`  - Products in Database: ${prodUpserted}`);
  console.log(`  - In-Stock Items: ${txCreated}`);
  console.log(`  - Total Stock Quantity: ${totalStock} units`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
