import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function testStatements() {
  const statements = [
    `DELETE FROM "FollowUp" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "CustomerComplaintItem" WHERE "complaintId" IN (SELECT id FROM "CustomerComplaint" WHERE "createdBy" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "submittedBy" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')) OR "orderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "SalesOrderLoss" WHERE "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "complaintId" IN (SELECT id FROM "CustomerComplaint" WHERE "createdBy" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "submittedBy" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')) OR "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "CustomerComplaint" WHERE "createdBy" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "submittedBy" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')`,
    `DELETE FROM "QCInspection" WHERE "workOrderId" IN (SELECT id FROM "WorkOrder" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))))`,
    `DELETE FROM "ProductionBatch" WHERE "workOrderId" IN (SELECT id FROM "WorkOrder" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))))`,
    `DELETE FROM "ProductionShiftEntry" WHERE "workOrderId" IN (SELECT id FROM "WorkOrder" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))))`,
    `DELETE FROM "ProductionScrapEntry" WHERE "workOrderId" IN (SELECT id FROM "WorkOrder" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))))`,
    `DELETE FROM "ProductionStatusHistory" WHERE "workOrderId" IN (SELECT id FROM "WorkOrder" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))))`,
    `DELETE FROM "FinishedGoods" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "WorkOrder" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))` ,
    `DELETE FROM "ProductionPlan" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "DispatchItem" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "Dispatch" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "InvoiceItem" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "SalesInvoice" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "CustomerPaymentAllocation" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "CustomerPayment" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SalesReturnItem" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "SalesReturn" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "ReplacementRequestItem" WHERE "salesOrderItemId" IN (SELECT id FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "ReplacementRequest" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "ReplacementOrder" WHERE "originalSalesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SalesOrderAllocation" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SalesOrderCreditReview" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "OrderAmendment" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SalesOrderHistory" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SalesOrderItem" WHERE "salesOrderId" IN (SELECT id FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SalesOrder" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')`,
    `DELETE FROM "QuotationItem" WHERE "quotationId" IN (SELECT id FROM "Quotation" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "QuotationTerm" WHERE "quotationId" IN (SELECT id FROM "Quotation" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "Quotation" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "SampleHistory" WHERE "sampleRequestId" IN (SELECT id FROM "SampleRequest" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "SampleItem" WHERE "sampleRequestId" IN (SELECT id FROM "SampleRequest" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')))`,
    `DELETE FROM "SampleRequest" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "LeadActivity" WHERE "leadId" IN (SELECT id FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com'))`,
    `DELETE FROM "Lead" WHERE "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "salesExecutiveId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "assignedToId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')`,
    `DELETE FROM "SalesTarget" WHERE "salespersonId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com') OR "createdById" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')`,
    `DELETE FROM "DeviceSession" WHERE "userId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')`,
    `DELETE FROM "RefreshSession" WHERE "userId" = (SELECT id FROM "User" WHERE LOWER(email) = 'supersales1@himalayaerp.com')`
  ];

  for (const s of statements) {
    await prisma.$executeRawUnsafe(s);
  }
  console.log('ALL STATEMENTS EXECUTED SUCCESSFULLY!');
  await prisma.$disconnect();
}

testStatements().catch(e => { console.error(e); process.exit(1); });
