export const INITIAL_ERP_STATE = {
  version: 'v3',
  eventStore: [],
  reproductions: [],
  purchaseOrders: [],
  leads: [],
  samples: [],
  quotations: [],
  orders: [],
  workOrders: [],
  materialRequests: [],
  customers: [],
  rawInventory: [],
  finishedInventory: [],
  dispatches: [],
  payments: [],
  expenses: [],
  employees: [],
  shifts: [],
  exitClearances: [],
  users: [],
  roles: [],
  settings: {
    companyName: 'Himalaya Enterprises',
    companyAddress: '123 Industrial Area, Phase 1, Haridwar',
    currency: '₹',
    taxRate: 18,
    emailNotifications: true,
    smsNotifications: false,
    fiscalYearStart: 'April',
    emailConfig: 'smtp.himalaya.com',
    smsConfig: 'http://smsapi.himalaya.com',
    salesTargets: {},
    thresholds: {
      excellent: 100,
      good: 70,
      risk: 40
    },
    alertsConfig: {
      productionDelayDays: 3,
      dispatchDelayDays: 5,
      paymentOverdueDays: 7,
      noFollowUpDays: 2
    }
  },
  leaves: [],
  notifications: [],
  auditLogs: [],
  paymentReminders: [],
  reminders: [],
  productCatalog: [],
  disabledModules: [],
  directOrders: [],
  directQuotes: [],
  machines: []
};
