const isMaterialMatch = (invName, reqName) => {
  const inv = (invName || '').toLowerCase();
  const req = (reqName || '').toLowerCase();
  if (inv === req) return true;
  if (inv.includes(req) || req.includes(inv)) return true;
  if (req === 'cement' && inv.includes('cement')) return true;
  if (req === 'sand' && inv.includes('sand')) return true;
  if (req === 'aggregate' && inv.includes('aggregate')) return true;
  return false;
};

export const inventoryReducer = (state, action) => {
  switch (action.type) {
    case 'CREATE_MATERIAL_REQUEST':
      return {
        ...state,
        materialRequests: [...state.materialRequests, action.payload]
      };

    case 'APPROVE_MATERIAL_REQUEST': {
      const { id, status, materials } = action.payload;
      const previousRequest = state.materialRequests.find(mr => mr.id === id);
      
      let updatedRawInventory = [...state.rawInventory];
      if (status === 'Approved' && (!previousRequest || previousRequest.status !== 'Approved')) {
        materials.forEach(m => {
          updatedRawInventory = updatedRawInventory.map(inv => 
            isMaterialMatch(inv.material, m.materialName)
              ? { ...inv, reserved: (inv.reserved || 0) + m.quantityApproved }
              : inv
          );
        });
      }

      return {
        ...state,
        materialRequests: state.materialRequests.map(mr => 
          mr.id === id ? { ...mr, ...action.payload } : mr
        ),
        rawInventory: updatedRawInventory
      };
    }

    case 'ISSUE_MATERIAL': {
      const { requestId, materialsIssued } = action.payload;
      const requestObj = state.materialRequests.find(mr => mr.id === requestId);
      
      const updatedRequests = state.materialRequests.map(mr => 
        mr.id === requestId 
          ? { 
              ...mr, 
              status: 'Issued', 
              materials: mr.materials.map(m => {
                const issued = materialsIssued.find(i => isMaterialMatch(i.materialName, m.materialName));
                return issued ? { ...m, quantityApproved: issued.quantityIssued } : m;
              }) 
            } 
          : mr
      );

      // Deduct from RawInventory
      let updatedRawInventory = [...state.rawInventory];
      materialsIssued.forEach(issued => {
        const reqMaterial = requestObj?.materials?.find(m => isMaterialMatch(m.materialName, issued.materialName));
        const previouslyReserved = reqMaterial ? reqMaterial.quantityApproved : issued.quantityIssued;

        updatedRawInventory = updatedRawInventory.map(inv => 
          isMaterialMatch(inv.material, issued.materialName)
            ? { 
                ...inv, 
                stock: Math.max(0, inv.stock - issued.quantityIssued),
                reserved: Math.max(0, (inv.reserved || 0) - previouslyReserved)
              }
            : inv
        );
      });

      return {
        ...state,
        materialRequests: updatedRequests,
        rawInventory: updatedRawInventory
      };
    }

    case 'ADJUST_STOCK': {
      const { material, stock } = action.payload;
      const isRaw = state.rawInventory.some(inv => inv.material.toLowerCase() === material.toLowerCase());
      const isFinished = state.finishedInventory.some(inv => inv.product.toLowerCase() === material.toLowerCase());

      if (isRaw) {
        return {
          ...state,
          rawInventory: state.rawInventory.map(inv => 
            inv.material.toLowerCase() === material.toLowerCase() ? { ...inv, stock } : inv
          )
        };
      } else if (isFinished) {
        return {
          ...state,
          finishedInventory: state.finishedInventory.map(inv => 
            inv.product.toLowerCase() === material.toLowerCase() ? { ...inv, stock } : inv
          )
        };
      }
      return state;
    }

    case 'RESTOCK_MATERIAL':
      return {
        ...state,
        rawInventory: state.rawInventory.map(inv => 
          inv.material.toLowerCase() === action.payload.material.toLowerCase()
            ? { ...inv, stock: inv.stock + action.payload.amount }
            : inv
        )
      };

    case 'CREATE_PO_REQUEST':
      return {
        ...state,
        purchaseOrders: [...(state.purchaseOrders || []), action.payload]
      };

    case 'CREATE_PO': {
      const { id, items, history } = action.payload;
      return {
        ...state,
        purchaseOrders: (state.purchaseOrders || []).map(po => 
          po.id === id 
            ? { 
                ...po, 
                items, 
                status: 'SENT_TO_STORE',
                history: history || [...(po.history || []), { stage: 'PO_CREATED', timestamp: Date.now(), remarks: 'Official Purchase Order generated by Finance and dispatched to Store.' }]
              } 
            : po
        )
      };
    }

    case 'UPDATE_PO': {
      const po = (state.purchaseOrders || []).find(p => p.id === action.payload.id);
      const updatedInventory = [...state.rawInventory];
      
      const isApproved = action.payload.status === 'COMPLETED' || action.payload.status === 'PARTIALLY_RECEIVED';
      let updatedItems = action.payload.items || (po ? po.items : []);
      
      if (isApproved && po) {
        updatedItems = updatedItems.map(item => {
          const oldItem = po.items.find(i => i.name.toLowerCase() === item.name.toLowerCase());
          const prevCredited = Number(oldItem?.creditedQuantity ?? 0);
          const currentReceived = Number(item.quantity_received ?? item.receivedQuantity ?? 0);
          const diff = Math.max(0, currentReceived - prevCredited);
          
          if (diff > 0) {
            const index = updatedInventory.findIndex(i => i.material.toLowerCase() === item.name.toLowerCase());
            if (index !== -1) {
              updatedInventory[index].stock += diff;
            }
          }
          
          return {
            ...item,
            creditedQuantity: currentReceived
          };
        });
      }
      
      return {
        ...state,
        rawInventory: updatedInventory,
        purchaseOrders: (state.purchaseOrders || []).map(p => 
          p.id === action.payload.id 
            ? { ...p, ...action.payload, items: updatedItems } 
            : p
        )
      };
    }
    case 'ADD_RAW_MATERIAL': {
      const { id, code, material, category, unit, reorderLevel, rate, description } = action.payload;
      const newMaterial = {
        id: id || 'RM-' + Math.floor(1000 + Math.random() * 9000),
        code,
        material,
        category,
        unit,
        stock: 0,
        reorderLevel: Number(reorderLevel) || 0,
        rate: Number(rate) || 0,
        description: description || '',
        transactions: []
      };
      return {
        ...state,
        rawInventory: [...(state.rawInventory || []), newMaterial]
      };
    }

    case 'EDIT_RAW_MATERIAL': {
      const { id, code, material, category, unit, reorderLevel, rate, description, oldMaterial } = action.payload;
      return {
        ...state,
        rawInventory: (state.rawInventory || []).map(inv => {
          const match = id 
            ? inv.id === id 
            : (inv.material.toLowerCase() === oldMaterial.toLowerCase() || inv.material.toLowerCase() === material.toLowerCase());
          if (match) {
            return {
              ...inv,
              code,
              material,
              category,
              unit,
              reorderLevel: Number(reorderLevel) || 0,
              rate: Number(rate) || 0,
              description: description || ''
            };
          }
          return inv;
        })
      };
    }

    case 'DELETE_RAW_MATERIAL': {
      const { material, id } = action.payload;
      return {
        ...state,
        rawInventory: (state.rawInventory || []).filter(inv => {
          const match = id ? inv.id === id : inv.material.toLowerCase() === material.toLowerCase();
          if (match) {
            // Block deletion if there are transactions
            if (inv.transactions && inv.transactions.length > 0) {
              return true; // keep it (meaning deletion is blocked)
            }
            return false; // delete it
          }
          return true; // keep it
        })
      };
    }

    case 'RECORD_STOCK_TRANSACTION': {
      const { id, material, type, quantity, rate, date, supplier, reference, remarks } = action.payload;
      return {
        ...state,
        rawInventory: (state.rawInventory || []).map(inv => {
          if (inv.material.toLowerCase() === material.toLowerCase()) {
            let newStock = inv.stock || 0;
            const qtyNum = Number(quantity) || 0;
            const rateNum = Number(rate) || inv.rate || 0;
            
            if (type === 'Stock In') {
              newStock += qtyNum;
            } else if (type === 'Stock Out') {
              newStock = Math.max(0, newStock - qtyNum);
            } else if (type === 'Adjustment') {
              newStock = qtyNum;
            }

            const newTx = {
              id: id || 'TX-' + Math.floor(1000 + Math.random() * 9000),
              type,
              quantity: qtyNum,
              rate: rateNum,
              date: date || new Date().toISOString().split('T')[0],
              supplier: supplier || '',
              reference: reference || '',
              remarks: remarks || ''
            };

            return {
              ...inv,
              stock: newStock,
              transactions: [...(inv.transactions || []), newTx]
            };
          }
          return inv;
        })
      };
    }

    default:
      return state;
  }
};
