var R=require("../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/sales/leads/[id]/edit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__efd25a0e._.js")
R.c("server/chunks/ssr/node_modules_05136449._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ed0865a8._.js")
R.c("server/chunks/ssr/app_0ef037c1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__748e2584._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_(dashboard)_layout_tsx_3fcfbfb4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6a2d60b0._.js")
R.c("server/chunks/ssr/_993f36f0._.js")
R.c("server/chunks/ssr/_a8f8eea8._.js")
R.m(349980)
R.m(838493)
module.exports=R.m(838493).exports
