import {
  Injectable,
  CanActivate,
  ExecutionContext,
  ForbiddenException,
} from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { PERMISSIONS_KEY } from '../decorators/permissions.decorator';
import { PrismaService } from '../../database/prisma.service';
import { IS_PUBLIC_KEY } from '../decorators/public.decorator';
import { IS_OPTIONAL_AUTH_KEY } from '../decorators/optional-auth.decorator';

interface UserPayload {
  sub?: string;
  role?: string;
  permissions?: string[];
}

@Injectable()
export class PermissionsGuard implements CanActivate {
  constructor(
    private reflector: Reflector,
    private prisma: PrismaService,
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);
    const isOptional = this.reflector.getAllAndOverride<boolean>(
      IS_OPTIONAL_AUTH_KEY,
      [context.getHandler(), context.getClass()],
    );

    if (isPublic) {
      return true;
    }

    const requiredPermissions = this.reflector.getAllAndOverride<string[]>(
      PERMISSIONS_KEY,
      [context.getHandler(), context.getClass()],
    );

    const req = context.switchToHttp().getRequest<{ user?: UserPayload }>();
    const user = req.user;

    if (!requiredPermissions || requiredPermissions.length === 0) {
      if (isOptional) return true;
      if (!user || !user.sub) {
        throw new ForbiddenException('Authentication required');
      }
      return true;
    }

    if (!user || !user.sub) {
      if (isOptional) return true;
      throw new ForbiddenException('Insufficient permissions');
    }

    // Normalized Role Check from JWT
    let normalizedRole = String(user.role || '')
      .toUpperCase()
      .replace(/[\s-]+/g, '_');
    if (
      normalizedRole === 'SUPER_ADMIN' ||
      normalizedRole === 'SUPERADMIN' ||
      normalizedRole === 'ADMIN' ||
      normalizedRole.includes('SUPER_ADMIN') ||
      normalizedRole.includes('SUPERADMIN')
    ) {
      return true;
    }
    if (
      normalizedRole.startsWith('SUPER_SALES') ||
      normalizedRole.startsWith('SUPERSALES')
    ) {
      normalizedRole = 'SUPER_SALES';
    } else if (
      normalizedRole.startsWith('SALES_EXEC') ||
      normalizedRole === 'SALES'
    ) {
      normalizedRole = 'SALES_EXECUTIVE';
    }

    // Merge permissions from JWT payload AND live Database
    const userPermSet = new Set<string>(
      Array.isArray(user.permissions) ? user.permissions : [],
    );

    try {
      let dbRole: any = null;

      // 1. Primary lookup by user ID (sub)
      if (user.sub) {
        const dbUser = await this.prisma.user.findUnique({
          where: { id: user.sub },
          include: {
            role: {
              include: {
                rolePermissions: {
                  include: { permission: true },
                },
              },
            },
          },
        });
        if (dbUser?.role) {
          dbRole = dbUser.role;
        }
      }

      // 2. Secondary lookup by role code or name
      if (!dbRole && user.role) {
        dbRole = await this.prisma.role.findFirst({
          where: {
            OR: [
              { code: user.role },
              { code: normalizedRole },
              { name: user.role },
            ],
          },
          include: {
            rolePermissions: {
              include: { permission: true },
            },
          },
        });
      }

      if (dbRole) {
        let dbRoleCode = String(dbRole.code || '')
          .toUpperCase()
          .replace(/[\s-]+/g, '_');
        if (
          dbRoleCode === 'SUPER_ADMIN' ||
          dbRoleCode === 'SUPERADMIN' ||
          dbRoleCode === 'ADMIN' ||
          dbRoleCode.includes('SUPER_ADMIN') ||
          dbRoleCode.includes('SUPERADMIN')
        ) {
          return true;
        }
        if (
          dbRoleCode.startsWith('SUPER_SALES') ||
          dbRoleCode.startsWith('SUPERSALES')
        ) {
          dbRoleCode = 'SUPER_SALES';
        } else if (
          dbRoleCode.startsWith('SALES_EXEC') ||
          dbRoleCode === 'SALES'
        ) {
          dbRoleCode = 'SALES_EXECUTIVE';
        }

        for (const rp of dbRole.rolePermissions || []) {
          if (rp.permission?.code) {
            userPermSet.add(rp.permission.code);
          }
        }
      }
    } catch (err) {
      // Ignore DB lookup error and fall back to collected set
    }

    // Role default baseline permissions for all organizational departments
    if (
      normalizedRole === 'SUPER_SALES' ||
      normalizedRole.includes('SUPER_SALES') ||
      normalizedRole.includes('SUPERSALES')
    ) {
      [
        'sales.orders.read',
        'sales.orders.create',
        'sales.orders.update',
        'sales.orders.approve',
        'sales.orders.cancel',
        'sales.leads.read',
        'sales.leads.create',
        'sales.leads.update',
        'sales.leads.manage',
        'crm.leads.read',
        'sales.customers.read',
        'sales.customers.create',
        'sales.customers.update',
        'crm.customers.read',
        'sales.quotations.read',
        'sales.quotations.create',
        'sales.quotations.update',
        'crm.quotations.read',
        'crm.quotations.create',
        'crm.quotations.update',
        'crm.quotations.send',
        'crm.quotations.convert',
        'crm.quotations.accept',
        'sales.targets.read',
        'sales.targets.create',
        'sales.targets.update',
        'admin.samples.read',
        'admin.samples.create',
        'admin.samples.update',
        'samples.read',
        'samples.create',
        'samples.update',
        'sales.samples.read',
        'sales.samples.create',
        'admin.salesreturns.read',
        'admin.salesreturns.create',
        'admin.salesreturns.update',
        'sales.salesreturns.read',
        'sales.salesreturns.create',
        'sales.salesreturns.update',
        'sales.returns.read',
        'sales.returns.create',
        'sales-returns.read',
        'sales.returns.manage',
        'sales.customercomplaints.read',
        'sales.customercomplaints.create',
        'sales.complaints.read',
        'sales.complaints.create',
        'admin.replacements.read',
        'admin.replacements.create',
        'admin.replacements.update',
        'admin.replacements.approve',
        'sales.salesreports.read',
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'finance.read',
        'finance.payment.read',
        'finance.payments.read',
        'finance.payment.update',
        'finance.payments.update',
        'finance.payment.verify',
        'finance.payment.reject',
        'finance.payments.manage',
        'finance.sales-analytics.read',
        'user.read',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'SALES_EXECUTIVE' ||
      normalizedRole.includes('SALES')
    ) {
      [
        'sales.orders.read',
        'sales.orders.create',
        'sales.orders.update',
        'sales.orders.approve',
        'sales.leads.read',
        'sales.leads.create',
        'sales.leads.update',
        'sales.leads.manage',
        'crm.leads.read',
        'sales.customers.read',
        'sales.customers.create',
        'sales.customers.update',
        'crm.customers.read',
        'sales.quotations.read',
        'sales.quotations.create',
        'sales.quotations.update',
        'crm.quotations.read',
        'crm.quotations.create',
        'crm.quotations.update',
        'crm.quotations.send',
        'crm.quotations.convert',
        'crm.quotations.accept',
        'sales.targets.read',
        'sales.salesreports.read',
        'sales.reports.read',
        'admin.samples.read',
        'admin.samples.create',
        'admin.samples.update',
        'samples.read',
        'samples.create',
        'samples.update',
        'sales.samples.read',
        'sales.samples.create',
        'admin.salesreturns.read',
        'admin.salesreturns.create',
        'admin.salesreturns.update',
        'sales.salesreturns.read',
        'sales.salesreturns.create',
        'sales.salesreturns.update',
        'sales.returns.read',
        'sales.returns.create',
        'sales-returns.read',
        'sales.returns.manage',
        'sales.customercomplaints.read',
        'sales.customercomplaints.create',
        'sales.complaints.read',
        'sales.complaints.create',
        'admin.replacements.read',
        'admin.replacements.create',
        'finance.payment.read',
        'finance.payments.read',
        'finance.payment.create',
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'procurement.suppliers.read',
        'suppliers.read',
        'user.read',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'PLANT_HEAD' ||
      normalizedRole === 'PLANTHEAD' ||
      normalizedRole.includes('PLANT_HEAD') ||
      normalizedRole.includes('PLANTHEAD') ||
      normalizedRole === 'PLANT_MANAGER' ||
      normalizedRole === 'FACTORY_MANAGER'
    ) {
      [
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'planthead.dashboard.read',
        'admin.planthead.create',
        'planthead.create',
        'plant-head.create',
        'admin.materialrequests.read',
        'admin.materialrequests.create',
        'admin.materialrequests.approve',
        'admin.materialrequests.reject',
        'admin.materialrequests.update',
        'materialrequests.read',
        'materialrequests.create',
        'materialrequests.approve',
        'materialrequests.reject',
        'store.materialrequests.read',
        'production.plan.read',
        'production.plans.read',
        'production.plan.create',
        'production.plan.approve',
        'production.plan.release',
        'production.workorder.read',
        'production.workorders.read',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.workorder.start',
        'production.workorder.complete',
        'production.workorder.update',
        'production.floor.read',
        'production.floor.create',
        'production.floor.update',
        'production.productionworkflow.read',
        'production.productionworkflow.create',
        'production.finishedgoods.read',
        'qc.inspections.read',
        'qc.inspections.create',
        'qc.inspections.approve',
        'qc.inspections.reject',
        'production.qc.read',
        'production.qc.approve',
        'production.qc.reject',
        'inventory.stock.read',
        'inventory.inventory.read',
        'inventory.warehouses.read',
        'admin.products.read',
        'products.read',
        'procurement.suppliers.read',
        'procurement.indents.read',
        'procurement.indents.create',
        'procurement.indents.update',
        'procurement.indents.approve',
        'procurement.indents.reject',
        'procurement.indents.override',
        'procurement.purchase_orders.read',
        'procurement.purchase-orders.read',
        'procurement.purchase_orders.update',
        'procurement.purchase_orders.approve',
        'procurement.grns.read',
        'procurement.grns.update',
        'procurement.procurement.read',
        'procurement.procurement.create',
        'procurement.procurement.reject',
        'procurement.audit.read',
        'audit.read',
        'admin.audit.read',
        'sales.orders.read',
        'sales.orders.update',
        'sales.orders.approve',
        'user.read',
        // Recruitment Permissions for Plant Head Indents:
        'hr.recruitment.read',
        'hr.recruitment.create',
        'hr.recruitment.update',
        'hr.recruitment.requests.create',
        'hr.recruitment.requests.read.all',
        'hr.recruitment.requests.read.own',
        'hr.recruitment.requests.update.own',
        'hr.recruitment.requests.update',
        'hr.recruitment.requests.withdraw',
        'hr.recruitment.requests.process',
        'hr.recruitment.requests.return',
        'hr.recruitment.requests.reject',
        'hr.recruitment.requests.fulfil',
        'hr.recruitment.candidates.create',
        'hr.recruitment.candidates.update',
        'admin.recruitment.read',
        'admin.recruitment.create',
        'admin.recruitment.update',
        'recruitment.read',
        'recruitment.create',
        'recruitment.update',
        // HR Employee & Department Permissions for Plant Head:
        'hr.employees.read',
        'hr.employees.create',
        'hr.employees.update',
        'hr.departments.read',
        'hr.locations.read',
        'hr.attendance.read',
        'hr.attendance.update',
        'hr.attendance.approve',
        'hr.leaves.read',
        'hr.leaves.update',
        'hr.leaves.approve',
        'hr.leaves.create',
        'attendance.read',
        'attendance.update',
        'attendance.approve',
        'employees.read',
        'departments.read',
        'locations.read',
        // Complaints & Plant Operations:
        'sales.customercomplaints.read',
        'sales.complaints.read',
        'sales.customercomplaints.update',
        'sales.complaints.update',
        'qc.failures.read',
        'qc.failures.update',
        'qc.testing.read',
        'qc.testing.create',
        'qc.testing.update',
        'reports.daily.read',
        'reports.daily.create',
        'daily-reports.read',
        'daily-reports.create',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'PRODUCTION' ||
      normalizedRole.includes('PRODUCTION') ||
      normalizedRole === 'PRODUCTION_MANAGER' ||
      normalizedRole === 'PRODUCTION_PLANNER' ||
      normalizedRole === 'PRODUCTION_SUPERVISOR'
    ) {
      [
        'production.plan.read',
        'production.plans.read',
        'production.plan.create',
        'production.plan.approve',
        'production.plan.release',
        'production.workorder.read',
        'production.workorders.read',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.workorder.start',
        'production.workorder.complete',
        'production.workorder.update',
        'production.floor.read',
        'production.floor.create',
        'production.floor.update',
        'production.floor.start',
        'production.floor.complete',
        'production.productionworkflow.read',
        'production.productionworkflow.create',
        'production.finishedgoods.read',
        'production.qc.read',
        'qc.inspections.read',
        'admin.materialrequests.read',
        'admin.materialrequests.create',
        'admin.materialrequests.update',
        'materialrequests.read',
        'materialrequests.create',
        'production.materialrequests.read',
        'production.materialrequests.create',
        'production.materialrequest.read',
        'production.materialrequest.create',
        'inventory.stock.read',
        'inventory.inventory.read',
        'inventory.warehouses.read',
        'admin.products.read',
        'products.read',
        'procurement.suppliers.read',
        'sales.orders.read',
        'sales.orders.update',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'user.read',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'DISPATCH_EXECUTIVE' ||
      normalizedRole.includes('DISPATCH') ||
      normalizedRole === 'LOGISTICS' ||
      normalizedRole === 'DISPATCH_2' ||
      normalizedRole === 'DISPATCH_MANAGER'
    ) {
      [
        'logistics.dispatches.read',
        'logistics.dispatches.create',
        'logistics.dispatches.update',
        'logistics.dispatches.manage',
        'logistics.dispatches.start-delivery',
        'logistics.dispatches.confirm-delivery',
        'dispatch.shipments.read',
        'dispatch.shipments.create',
        'dispatch.delivery.verify',
        'dispatch.update',
        'admin.samples.read',
        'admin.samples.update',
        'samples.read',
        'samples.update',
        'sales.samples.read',
        'admin.salesreturns.read',
        'sales.salesreturns.read',
        'sales.returns.read',
        'sales-returns.read',
        'sales.returns.manage',
        'sales.orders.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'inventory.warehouses.read',
        'production.finishedgoods.read',
        'production.workorder.read',
        'production.workorders.read',
        'user.read',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'STORE_MANAGER' ||
      normalizedRole.includes('STORE') ||
      normalizedRole === 'STORE_EXECUTIVE' ||
      normalizedRole === 'STORE_KEEPER'
    ) {
      [
        'store.materialrequests.read',
        'store.materialrequests.approve',
        'store.materialrequests.create',
        'admin.materialrequests.read',
        'admin.materialrequests.create',
        'admin.materialrequests.approve',
        'admin.materialrequests.reject',
        'admin.materialrequests.update',
        'materialrequests.read',
        'materialrequests.create',
        'materialrequests.approve',
        'materialrequests.reject',
        'materialrequests.update',
        'inventory.stock.read',
        'inventory.inventory.read',
        'inventory.warehouses.read',
        'admin.products.read',
        'products.read',
        'store.brand-analysis.read',
        'store.brand-analysis.create',
        'admin.storereports.read',
        'procurement.grns.read',
        'procurement.grns.create',
        'procurement.grns.update',
        'procurement.suppliers.read',
        'procurement.indents.read',
        'procurement.indents.create',
        'procurement.indents.update',
        'procurement.purchase_orders.read',
        'procurement.purchase-orders.read',
        'procurement.procurement.read',
        'procurement.procurement.create',
        'procurement.audit.read',
        'audit.read',
        'admin.audit.read',
        'production.workorder.read',
        'logistics.dispatches.read',
        'sales.returns.read',
        'sales.returns.update',
        'sales-returns.read',
        'user.read',
        'qc.inspection.read',
        'qc.inspections.read',
        'production.qc.read',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'FINANCE' ||
      normalizedRole.includes('FINANCE') ||
      normalizedRole === 'FINANCE_MANAGER' ||
      normalizedRole === 'FINANCE_EXECUTIVE' ||
      normalizedRole === 'ACCOUNTANT' ||
      normalizedRole === 'FINANCE_USER'
    ) {
      [
        'finance.read',
        'finance.payment.read',
        'finance.payments.read',
        'finance.payment.verify',
        'finance.payment.reject',
        'finance.payment.create',
        'finance.payments.manage',
        'finance.payment.update',
        'finance.payments.update',
        'finance.invoices.read',
        'finance.invoices.create',
        'finance.invoices.update',
        'finance.invoice.read',
        'finance.invoice.create',
        'finance.invoice.update',
        'finance.ledger.read',
        'finance.brand-analysis.read',
        'finance.brand-analysis.start',
        'finance.brand-analysis.complete',
        'finance.sales-analytics.read',
        'finance.sales-analytics.activity.read',
        'finance.sales-analytics.receivables.read',
        'finance.sales-analytics.export',
        'finance.salary.manage',
        'finance.salary.view',
        'finance.salary.read',
        'finance.salary.disburse',
        'finance.reports.read',
        'sales.orders.read',
        'sales.customers.read',
        'logistics.dispatches.read',
        'procurement.indents.read',
        'procurement.indents.update',
        'procurement.indents.approve',
        'procurement.purchase_orders.read',
        'procurement.purchase-orders.read',
        'procurement.purchase_orders.create',
        'procurement.purchase_orders.update',
        'procurement.purchase_orders.approve',
        'procurement.grns.read',
        'procurement.grns.update',
        'procurement.invoices.read',
        'procurement.payments.read',
        'procurement.suppliers.read',
        'procurement.vendor_invoices.read',
        'procurement.vendor-invoices.read',
        'procurement.vendor_payments.read',
        'procurement.vendor-payments.read',
        'procurement.vendor_invoices.create',
        'procurement.vendor-invoices.create',
        'procurement.vendor_invoices.update',
        'procurement.vendor-invoices.update',
        'procurement.vendor_payments.create',
        'procurement.vendor-payments.create',
        'procurement.vendor_payments.update',
        'procurement.vendor-payments.update',
        'procurement.procurement.read',
        'procurement.procurement.create',
        'procurement.audit.read',
        'audit.read',
        'admin.audit.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'user.read',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'HR' ||
      normalizedRole.includes('HR') ||
      normalizedRole === 'HR_MANAGER' ||
      normalizedRole === 'HR_EXECUTIVE'
    ) {
      [
        'hr.read',
        'hr.employees.read',
        'hr.employees.create',
        'hr.employees.update',
        'hr.employees.delete',
        'hr.employees.status.update',
        'hr.employees.documents.read',
        'hr.employees.documents.upload',
        'hr.employees.documents.delete',
        'hr.employees.sensitive.read',
        'hr.departments.read',
        'hr.locations.read',
        'hr.recruitment.read',
        'hr.recruitment.create',
        'hr.recruitment.update',
        'hr.recruitment.requests.read.all',
        'hr.recruitment.requests.read.own',
        'hr.recruitment.requests.create',
        'hr.recruitment.requests.update',
        'hr.recruitment.requests.update.own',
        'hr.recruitment.requests.withdraw',
        'hr.recruitment.requests.process',
        'hr.recruitment.requests.return',
        'hr.recruitment.requests.reject',
        'hr.recruitment.requests.fulfil',
        'hr.recruitment.requests.override',
        'hr.recruitment.candidates.create',
        'hr.recruitment.candidates.update',
        'admin.recruitment.read',
        'admin.recruitment.create',
        'admin.recruitment.update',
        'recruitment.read',
        'recruitment.create',
        'recruitment.update',
        'hr.attendance.read',
        'hr.attendance.update',
        'hr.attendance.approve',
        'hr.leaves.read',
        'hr.leaves.update',
        'hr.leaves.approve',
        'hr.leaves.create',
        'hr.salary.read',
        'hr.salary.prepare',
        'hr.salary.create',
        'hr.salary.edit',
        'hr.salary.submit',
        'hr.salary.update',
        'hr.payroll.read',
        'hr.payroll.prepare',
        'hr.payroll.create',
        'hr.payroll.edit',
        'hr.payroll.submit',
        'hr.payroll.update',
        'hr.salary-structure.read',
        'hr.salary-structure.create',
        'hr.salary-structure.update',
        'hr.roles.read',
        'hr.roles.create',
        'hr.roles.update',
        'hr.exit.read',
        'hr.exit.update',
        'admin.notifications.read',
        'admin.notifications.create',
        'notifications.read',
        'notifications.create',
        'notifications.broadcast',
        'audit.read',
        'admin.audit.read',
        'user.read',
        'user.create',
        'user.update',
      ].forEach((p) => userPermSet.add(p));
    }

    if (
      normalizedRole === 'QC' ||
      normalizedRole.includes('QC') ||
      normalizedRole === 'QC_MANAGER' ||
      normalizedRole === 'QC_INSPECTOR' ||
      normalizedRole === 'QC_ENGINEER'
    ) {
      [
        'qc.inspections.read',
        'qc.inspections.create',
        'qc.inspections.update',
        'qc.inspections.approve',
        'qc.inspections.reject',
        'qc.inspection.read',
        'qc.inspection.approve',
        'qc.inspection.reject',
        'production.qc.read',
        'production.qc.approve',
        'production.qc.reject',
        'production.workorder.read',
        'production.workorders.read',
        'production.floor.read',
        'production.finishedgoods.read',
        'inventory.stock.read',
        'admin.products.read',
        'products.read',
        'user.read',
      ].forEach((p) => userPermSet.add(p));
    }

    const allUserPerms = Array.from(userPermSet);

    const PERMISSION_ALIASES: Record<string, string[]> = {
      'procurement.audit.read': [
        'procurement.audit.read',
        'audit.read',
        'admin.audit.read',
        'admin.read',
        'super-admin.read',
        'finance.read',
        'store.read',
        'planthead.read',
        'admin.planthead.read',
      ],
      'admin.audit.read': [
        'procurement.audit.read',
        'audit.read',
        'admin.audit.read',
        'admin.read',
        'super-admin.read',
        'finance.read',
        'store.read',
        'planthead.read',
        'admin.planthead.read',
      ],
      'audit.read': [
        'procurement.audit.read',
        'audit.read',
        'admin.audit.read',
        'admin.read',
        'super-admin.read',
        'finance.read',
        'store.read',
        'planthead.read',
        'admin.planthead.read',
      ],
      'logistics.dispatches.read': [
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'dispatch.delivery.verify',
        'dispatch.update',
        'production.workorder.read',
        'production.work_orders.manage',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
      ],
      'logistics.dispatches.create': [
        'logistics.dispatches.create',
        'dispatch.shipments.create',
        'dispatch.update',
        'production.workorder.complete',
        'admin.read',
        'super-admin.read',
      ],
      'logistics.dispatches.start-delivery': [
        'logistics.dispatches.start-delivery',
        'logistics.dispatches.read',
        'dispatch.update',
        'dispatch.delivery.verify',
        'admin.read',
        'super-admin.read',
      ],
      'logistics.dispatches.confirm-delivery': [
        'logistics.dispatches.confirm-delivery',
        'logistics.dispatches.read',
        'dispatch.update',
        'dispatch.delivery.verify',
        'admin.read',
        'super-admin.read',
      ],
      'dispatch.shipments.read': [
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'dispatch.delivery.verify',
        'dispatch.update',
        'production.workorder.read',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
      ],
      'dispatch.shipments.create': [
        'logistics.dispatches.create',
        'dispatch.shipments.create',
        'dispatch.update',
        'admin.read',
        'super-admin.read',
      ],
      'dispatch.delivery.verify': [
        'logistics.dispatches.confirm-delivery',
        'logistics.dispatches.read',
        'dispatch.delivery.verify',
        'dispatch.update',
        'admin.read',
        'super-admin.read',
      ],
      'dispatch.update': [
        'logistics.dispatches.update',
        'logistics.dispatches.read',
        'dispatch.update',
        'dispatch.delivery.verify',
        'admin.read',
        'super-admin.read',
      ],
      'sales.salesreturns.read': [
        'sales.salesreturns.read',
        'admin.salesreturns.read',
        'sales.returns.read',
        'sales-returns.read',
        'sales.returns.manage',
        'sales.orders.read',
        'logistics.dispatches.read',
        'admin.read',
        'super-admin.read',
      ],
      'sales.salesreturns.create': [
        'sales.salesreturns.create',
        'admin.salesreturns.create',
        'sales.returns.create',
        'sales-returns.create',
        'sales.orders.create',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
      ],
      'sales.salesreturns.approve': [
        'sales.salesreturns.approve',
        'admin.salesreturns.approve',
        'sales.returns.approve',
        'sales.orders.approve',
        'admin.read',
        'super-admin.read',
      ],
      'sales.salesreturns.reject': [
        'sales.salesreturns.reject',
        'admin.salesreturns.reject',
        'sales.returns.reject',
        'sales.orders.reject',
        'admin.read',
        'super-admin.read',
      ],
      'sales.salesreturns.update': [
        'sales.salesreturns.update',
        'admin.salesreturns.update',
        'sales.returns.update',
        'sales.returns.manage',
        'logistics.dispatches.read',
        'admin.read',
        'super-admin.read',
      ],
      'admin.samples.read': [
        'admin.samples.read',
        'samples.read',
        'sales.samples.read',
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'sales.leads.read',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
      ],
      'admin.samples.create': [
        'admin.samples.create',
        'samples.create',
        'sales.samples.create',
        'sales.leads.create',
        'sales.orders.create',
        'admin.read',
        'super-admin.read',
      ],
      'admin.samples.update': [
        'admin.samples.update',
        'samples.update',
        'sales.samples.update',
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'sales.leads.update',
        'admin.read',
        'super-admin.read',
      ],
      'samples.read': [
        'admin.samples.read',
        'samples.read',
        'sales.samples.read',
        'logistics.dispatches.read',
        'dispatch.shipments.read',
        'sales.leads.read',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
      ],
      'admin.planthead.read': [
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'planthead.dashboard.read',
        'production.productionworkflow.read',
        'production.plan.read',
        'production.plans.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'sales.orders.read',
      ],
      'planthead.read': [
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'planthead.dashboard.read',
        'production.productionworkflow.read',
        'production.plan.read',
        'production.plans.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'sales.orders.read',
      ],
      'plant-head.read': [
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'planthead.dashboard.read',
        'production.productionworkflow.read',
        'production.plan.read',
        'production.plans.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'sales.orders.read',
      ],
      'planthead.dashboard.read': [
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'planthead.dashboard.read',
        'production.productionworkflow.read',
        'production.plan.read',
        'production.plans.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'sales.orders.read',
      ],
      'admin.planthead.create': [
        'admin.planthead.create',
        'planthead.create',
        'plant-head.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.plan.create',
        'production.plan.approve',
        'production.plans.create',
        'production.plan.release',
        'production.work_orders.manage',
      ],
      'planthead.create': [
        'admin.planthead.create',
        'planthead.create',
        'plant-head.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.plan.create',
        'production.plan.approve',
        'production.plans.create',
        'production.plan.release',
        'production.work_orders.manage',
      ],
      'plant-head.create': [
        'admin.planthead.create',
        'planthead.create',
        'plant-head.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.plan.create',
        'production.plan.approve',
        'production.plans.create',
        'production.plan.release',
        'production.work_orders.manage',
      ],
      'admin.products.read': [
        'admin.products.read',
        'products.read',
        'store.read',
        'finance.read',
        'sales.read',
        'inventory.stock.read',
        'admin.read',
        'super-admin.read',
      ],
      'products.read': [
        'admin.products.read',
        'products.read',
        'store.read',
        'finance.read',
        'sales.read',
        'inventory.stock.read',
        'admin.read',
        'super-admin.read',
      ],
      'inventory.warehouses.read': [
        'inventory.warehouses.read',
        'warehouses.read',
        'inventory.stock.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'warehouses.read': [
        'inventory.warehouses.read',
        'warehouses.read',
        'inventory.stock.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'procurement.suppliers.read': [
        'procurement.suppliers.read',
        'suppliers.read',
        'vendors.read',
        'store.read',
        'finance.read',
        'sales.read',
        'sales.orders.read',
        'sales.leads.read',
        'user.read',
        'admin.read',
        'super-admin.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'production.plan.read',
        'production.floor.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'suppliers.read': [
        'procurement.suppliers.read',
        'suppliers.read',
        'vendors.read',
        'store.read',
        'finance.read',
        'sales.read',
        'sales.orders.read',
        'sales.leads.read',
        'user.read',
        'admin.read',
        'super-admin.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'production.plan.read',
        'production.floor.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'inventory.inventory.read': [
        'inventory.inventory.read',
        'inventory.stock.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'inventory.stock.read': [
        'inventory.inventory.read',
        'inventory.stock.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'production.qc.read': [
        'production.qc.read',
        'qc.inspection.read',
        'qc.inspections.read',
        'store.read',
        'inventory.stock.read',
        'admin.read',
        'super-admin.read',
        'planthead.read',
        'plant-head.read',
        'admin.planthead.read',
      ],
      'qc.inspection.read': [
        'production.qc.read',
        'qc.inspection.read',
        'qc.inspections.read',
        'store.read',
        'inventory.stock.read',
        'admin.read',
        'super-admin.read',
        'planthead.read',
        'plant-head.read',
        'admin.planthead.read',
      ],
      'qc.inspections.read': [
        'production.qc.read',
        'qc.inspection.read',
        'qc.inspections.read',
        'store.read',
        'inventory.stock.read',
        'admin.read',
        'super-admin.read',
        'planthead.read',
        'plant-head.read',
        'admin.planthead.read',
      ],
      'production.productionworkflow.read': [
        'production.productionworkflow.read',
        'production.finishedgoods.read',
        'production.qc.read',
        'qc.inspection.read',
        'production.plan.read',
        'production.plans.read',
        'production.workorder.read',
        'production.work_orders.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'production.productionworkflow.create': [
        'production.productionworkflow.create',
        'production.productionworkflow.read',
        'production.floor.create',
        'production.floor.update',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.plan.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
      ],
      'production.floor.create': [
        'production.floor.create',
        'production.floor.update',
        'production.productionworkflow.create',
        'production.productionworkflow.read',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.plan.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
      ],
      'production.finishedgoods.read': [
        'production.productionworkflow.read',
        'production.finishedgoods.read',
        'production.qc.read',
        'qc.inspection.read',
        'production.plan.read',
        'production.plans.read',
        'production.workorder.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'production.plan.read': [
        'production.plan.read',
        'production.plans.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.productionworkflow.read',
        'production.floor.read',
        'production.workorder.read',
        'production.work_orders.manage',
      ],
      'production.plans.read': [
        'production.plan.read',
        'production.plans.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.productionworkflow.read',
        'production.floor.read',
        'production.workorder.read',
        'production.work_orders.manage',
      ],
      'production.plan.create': [
        'production.plan.create',
        'production.plans.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.floor.create',
      ],
      'production.plan.approve': [
        'production.plan.approve',
        'production.plans.approve',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'production.plan.release': [
        'production.plan.release',
        'production.plans.release',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
      ],
      'production.workorder.read': [
        'production.workorder.read',
        'production.workorders.read',
        'production.work_orders.read',
        'production.work_orders.manage',
        'production.workorder.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.productionworkflow.read',
        'production.floor.read',
        'production.plans.read',
        'production.plan.read',
        'dispatch.shipments.read',
        'dispatch.delivery.verify',
        'logistics.dispatches.read',
      ],
      'production.workorders.read': [
        'production.workorder.read',
        'production.workorders.read',
        'production.work_orders.read',
        'production.work_orders.manage',
        'production.workorder.manage',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'production.productionworkflow.read',
        'production.floor.read',
        'production.plans.read',
        'production.plan.read',
        'dispatch.shipments.read',
        'dispatch.delivery.verify',
        'logistics.dispatches.read',
      ],
      'production.workorder.start': [
        'production.workorder.start',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.floor.start',
        'production.productionworkflow.read',
        'production.plan.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'sales.orders.update',
      ],
      'production.workorder.complete': [
        'production.workorder.complete',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.floor.complete',
        'production.productionworkflow.read',
        'production.plan.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'sales.orders.update',
      ],
      'production.workorder.update': [
        'production.workorder.update',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.floor.update',
        'production.productionworkflow.read',
        'production.plan.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'sales.orders.update',
      ],
      'user.read': [
        'user.read',
        'store.read',
        'finance.read',
        'sales.orders.read',
        'admin.read',
        'hr.read',
        'super-admin.read',
        'plant.read',
        'planthead.read',
        'admin.planthead.read',
        'plant-head.read',
        'production.plans.read',
        'production.plan.read',
        'production.floor.read',
        'production.work_orders.manage',
        'common.dashboard.read',
      ],
      'finance.brand-analysis.read': [
        'finance.brand-analysis.read',
        'brand-analysis.read',
        'store.brand-analysis.read',
        'super-admin.brand-analysis.read',
        'store.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'finance.read',
        'finance.payment.read',
        'finance.invoices.read',
        'finance.ledger.read',
        'finance.payments.manage',
        'finance.sales-analytics.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.read': [
        'finance.read',
        'finance.brand-analysis.read',
        'finance.payment.read',
        'finance.invoices.read',
        'finance.ledger.read',
        'finance.payments.manage',
        'finance.sales-analytics.read',
        'finance.salary.manage',
        'finance.salary.view',
        'finance.reports.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.reports.read': [
        'finance.reports.read',
        'finance.read',
        'finance.sales-analytics.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payments.read': [
        'finance.payments.read',
        'finance.payment.read',
        'finance.payments.manage',
        'finance.payment.verify',
        'finance.payment.update',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payment.read': [
        'finance.payments.read',
        'finance.payment.read',
        'finance.payments.manage',
        'finance.payment.verify',
        'finance.payment.update',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payment.create': [
        'finance.payment.create',
        'finance.payments.create',
        'finance.payment.verify',
        'finance.payment.update',
        'finance.payments.manage',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payments.create': [
        'finance.payment.create',
        'finance.payments.create',
        'finance.payment.verify',
        'finance.payment.update',
        'finance.payments.manage',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payment.update': [
        'finance.payment.update',
        'finance.payments.update',
        'finance.payment.verify',
        'finance.payment.reject',
        'finance.payments.manage',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payments.update': [
        'finance.payment.update',
        'finance.payments.update',
        'finance.payment.verify',
        'finance.payment.reject',
        'finance.payments.manage',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payments.manage': [
        'finance.payments.manage',
        'finance.payment.update',
        'finance.payments.update',
        'finance.payment.verify',
        'finance.payment.reject',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payment.verify': [
        'finance.payment.verify',
        'finance.payment.update',
        'finance.payments.update',
        'finance.payments.manage',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.payment.reject': [
        'finance.payment.reject',
        'finance.payment.update',
        'finance.payments.update',
        'finance.payments.manage',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.invoice.read': [
        'finance.invoice.read',
        'finance.invoices.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.invoices.read': [
        'finance.invoice.read',
        'finance.invoices.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.invoice.create': [
        'finance.invoice.create',
        'finance.invoices.create',
        'finance.invoice.update',
        'finance.invoices.update',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.invoices.create': [
        'finance.invoice.create',
        'finance.invoices.create',
        'finance.invoice.update',
        'finance.invoices.update',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.invoice.update': [
        'finance.invoice.update',
        'finance.invoices.update',
        'finance.invoice.create',
        'finance.invoices.create',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.invoices.update': [
        'finance.invoice.update',
        'finance.invoices.update',
        'finance.invoice.create',
        'finance.invoices.create',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.ledger.read': [
        'finance.ledger.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.brand-analysis.start': [
        'finance.brand-analysis.start',
        'finance.brand-analysis.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.brand-analysis.complete': [
        'finance.brand-analysis.complete',
        'finance.brand-analysis.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'store.brand-analysis.read': [
        'finance.brand-analysis.read',
        'brand-analysis.read',
        'store.brand-analysis.read',
        'super-admin.brand-analysis.read',
        'store.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'admin.read',
        'super-admin.read',
      ],
      'super-admin.brand-analysis.read': [
        'finance.brand-analysis.read',
        'brand-analysis.read',
        'store.brand-analysis.read',
        'super-admin.brand-analysis.read',
        'store.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'admin.read',
        'super-admin.read',
        'finance.read',
      ],
      'store.brand-analysis.create': [
        'store.brand-analysis.create',
        'brand-analysis.create',
        'store.create',
        'store.read',
        'store.manage',
        'inventory.stock.read',
        'inventory.inventory.read',
        'procurement.create',
        'admin.read',
        'super-admin.read',
      ],
      'super-admin.brand-analysis.approve': [
        'super-admin.brand-analysis.approve',
        'brand-analysis.approve',
        'admin.approve',
        'admin.read',
        'super-admin.read',
      ],
      'super-admin.brand-analysis.reject': [
        'super-admin.brand-analysis.reject',
        'brand-analysis.reject',
        'admin.reject',
        'admin.read',
        'super-admin.read',
      ],
      'admin.replacements.create': [
        'admin.replacements.create',
        'sales.replacements.create',
        'replacements.create',
        'sales.orders.create',
        'sales.orders.read',
      ],
      'admin.replacements.read': [
        'admin.replacements.read',
        'sales.replacements.read',
        'replacements.read',
        'sales.orders.read',
      ],
      'admin.replacements.approve': [
        'admin.replacements.approve',
        'sales.replacements.approve',
        'replacements.approve',
        'sales.orders.approve',
        'sales.orders.read',
      ],
      'admin.replacements.reject': [
        'admin.replacements.reject',
        'sales.replacements.reject',
        'replacements.reject',
        'sales.orders.reject',
        'sales.orders.read',
      ],
      'admin.replacements.update': [
        'admin.replacements.update',
        'sales.replacements.update',
        'replacements.update',
        'sales.orders.update',
        'sales.orders.read',
      ],
      'production.qc.approve': [
        'production.qc.approve',
        'qc.inspection.approve',
        'qc.inspections.approve',
        'production.qc.read',
        'qc.inspection.read',
        'production.floor.complete',
      ],
      'qc.inspection.approve': [
        'production.qc.approve',
        'qc.inspection.approve',
        'qc.inspections.approve',
        'production.qc.read',
        'qc.inspection.read',
        'production.floor.complete',
      ],
      'production.qc.reject': [
        'production.qc.reject',
        'qc.inspection.reject',
        'qc.inspections.reject',
        'production.qc.read',
        'qc.inspection.read',
      ],
      'qc.inspection.reject': [
        'production.qc.reject',
        'qc.inspection.reject',
        'qc.inspections.reject',
        'production.qc.read',
        'qc.inspection.read',
      ],
      'sales.customercomplaints.read': [
        'sales.customercomplaints.read',
        'sales.complaints.read',
      ],
      'sales.complaints.read': [
        'sales.customercomplaints.read',
        'sales.complaints.read',
      ],
      'sales.customercomplaints.create': [
        'sales.customercomplaints.create',
        'sales.complaints.create',
      ],
      'sales.complaints.create': [
        'sales.customercomplaints.create',
        'sales.complaints.create',
      ],
      'admin.materialrequests.read': [
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'production.materialrequest.read',
        'store.materialrequests.read',
        'material_requests.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
      ],
      'materialrequests.read': [
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'production.materialrequest.read',
        'store.materialrequests.read',
        'material_requests.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
      ],
      'inventory.materialrequests.read': [
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'production.materialrequest.read',
        'store.materialrequests.read',
        'material_requests.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
      ],
      'production.materialrequests.read': [
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'production.materialrequest.read',
        'store.materialrequests.read',
        'material_requests.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.work_orders.manage',
      ],
      'admin.materialrequests.create': [
        'admin.materialrequests.create',
        'materialrequests.create',
        'inventory.materialrequests.create',
        'production.materialrequests.create',
        'production.materialrequest.create',
        'store.materialrequests.create',
        'material_requests.create',
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'production.floor.create',
        'production.work_orders.manage',
      ],
      'admin.materialrequests.approve': [
        'admin.materialrequests.approve',
        'materialrequests.approve',
        'inventory.materialrequests.approve',
        'production.materialrequests.approve',
        'store.materialrequests.approve',
        'material_requests.approve',
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'admin.materialrequests.reject': [
        'admin.materialrequests.reject',
        'materialrequests.reject',
        'inventory.materialrequests.reject',
        'production.materialrequests.reject',
        'store.materialrequests.reject',
        'material_requests.reject',
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'admin.materialrequests.update': [
        'admin.materialrequests.update',
        'materialrequests.update',
        'inventory.materialrequests.update',
        'production.materialrequests.update',
        'material_requests.update',
        'admin.materialrequests.approve',
        'materialrequests.approve',
        'admin.materialrequests.read',
        'materialrequests.read',
        'inventory.materialrequests.read',
        'production.materialrequests.read',
        'inventory.stock.read',
        'inventory.inventory.read',
      ],
      'sales.orders.read': [
        'sales.orders.read',
        'sales.order.read',
        'sales.read',
        'admin.read',
        'super-admin.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'dispatch.shipments.read',
      ],
      'sales.orders.create': ['sales.orders.create', 'sales.order.create'],
      'sales.orders.update': [
        'sales.orders.update',
        'sales.order.update',
        'sales.orders.approve',
        'sales.orders.create',
        'production.work_orders.manage',
        'production.workorder.manage',
        'production.workorder.start',
        'production.workorder.complete',
        'production.workorder.read',
        'production.productionworkflow.read',
        'production.plan.read',
        'production.floor.update',
        'planthead.read',
        'admin.planthead.read',
        'plant-head.read',
      ],
      'sales.leads.read': [
        'sales.leads.read',
        'crm.leads.read',
        'sales.read',
        'sales.leads.manage',
        'admin.read',
        'super-admin.read',
      ],
      'sales.customers.read': [
        'sales.customers.read',
        'crm.customers.read',
        'sales.read',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
      ],
      'crm.quotations.read': [
        'crm.quotations.read',
        'crm.quotation.read',
        'sales.quotations.read',
        'sales.quotation.read',
        'sales.read',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
        'finance.read',
      ],
      'sales.quotations.read': [
        'crm.quotations.read',
        'crm.quotation.read',
        'sales.quotations.read',
        'sales.quotation.read',
        'sales.read',
        'sales.orders.read',
        'admin.read',
        'super-admin.read',
        'finance.read',
      ],
      'crm.quotations.create': [
        'crm.quotations.create',
        'crm.quotation.create',
        'sales.quotations.create',
      ],
      'crm.quotations.update': [
        'crm.quotations.update',
        'crm.quotation.update',
        'sales.quotations.update',
      ],
      'crm.quotations.send': ['crm.quotations.send', 'crm.quotation.send'],
      'crm.quotations.convert': [
        'crm.quotations.convert',
        'crm.quotation.convert',
        'crm.quotations.update',
        'sales.orders.create',
      ],
      'crm.quotations.accept': [
        'crm.quotations.accept',
        'crm.quotation.accept',
        'crm.quotations.update',
        'sales.orders.create',
      ],
      'procurement.indents.read': [
        'procurement.indents.read',
        'procurement.procurement.read',
        'procurement.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'store.read',
        'finance.read',
        'finance.invoices.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.indents.create': [
        'procurement.indents.create',
        'procurement.indents.update',
        'procurement.procurement.create',
        'procurement.procurement.read',
        'store.materialrequests.create',
        'store.create',
        'store.read',
        'admin.planthead.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.indents.update': [
        'procurement.indents.update',
        'procurement.indents.approve',
        'procurement.indents.reject',
        'procurement.indents.create',
        'procurement.indents.manage',
        'procurement.procurement.read',
        'admin.planthead.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.indents.approve': [
        'procurement.indents.approve',
        'procurement.indents.update',
        'admin.planthead.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.indents.reject': [
        'procurement.indents.reject',
        'procurement.indents.update',
        'admin.planthead.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.purchase_orders.read': [
        'procurement.purchase_orders.read',
        'procurement.purchase-orders.read',
        'procurement.po.read',
        'procurement.procurement.read',
        'procurement.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.purchase-orders.read': [
        'procurement.purchase_orders.read',
        'procurement.purchase-orders.read',
        'procurement.po.read',
        'procurement.procurement.read',
        'procurement.read',
        'store.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.purchase_orders.create': [
        'procurement.purchase_orders.create',
        'procurement.purchase-orders.create',
        'procurement.po.create',
        'procurement.purchase_orders.update',
        'finance.invoices.create',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.purchase_orders.update': [
        'procurement.purchase_orders.update',
        'procurement.purchase-orders.update',
        'procurement.purchase_orders.approve',
        'procurement.purchase-orders.approve',
        'procurement.po.update',
        'procurement.po.approve',
        'finance.read',
        'finance.invoices.update',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.grns.read': [
        'procurement.grns.read',
        'procurement.grn.read',
        'procurement.procurement.read',
        'procurement.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
        'finance.read',
        'finance.invoices.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.invoices.read': [
        'procurement.invoices.read',
        'procurement.invoice.read',
        'procurement.vendor-invoices.read',
        'procurement.vendor_invoices.read',
        'procurement.procurement.read',
        'procurement.read',
        'finance.invoices.read',
        'finance.invoice.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.vendor-invoices.read': [
        'procurement.vendor-invoices.read',
        'procurement.vendor_invoices.read',
        'procurement.invoices.read',
        'procurement.invoice.read',
        'procurement.procurement.read',
        'procurement.read',
        'finance.invoices.read',
        'finance.invoice.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.vendor_invoices.read': [
        'procurement.vendor_invoices.read',
        'procurement.vendor-invoices.read',
        'procurement.invoices.read',
        'procurement.invoice.read',
        'procurement.procurement.read',
        'procurement.read',
        'finance.invoices.read',
        'finance.invoice.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.vendor_invoices.create': [
        'procurement.vendor_invoices.create',
        'procurement.vendor-invoices.create',
        'procurement.invoices.create',
        'procurement.invoice.create',
        'procurement.procurement.create',
        'procurement.create',
        'finance.invoices.create',
        'finance.invoice.create',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.vendor_invoices.update': [
        'procurement.vendor_invoices.update',
        'procurement.vendor-invoices.update',
        'procurement.invoices.update',
        'procurement.invoice.update',
        'procurement.procurement.update',
        'procurement.update',
        'finance.invoices.update',
        'finance.invoice.update',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.payments.read': [
        'procurement.payments.read',
        'procurement.payment.read',
        'procurement.vendor-payments.read',
        'procurement.vendor_payments.read',
        'procurement.procurement.read',
        'procurement.read',
        'finance.payments.manage',
        'finance.payment.read',
        'finance.payments.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.vendor-payments.read': [
        'procurement.vendor-payments.read',
        'procurement.vendor_payments.read',
        'procurement.payments.read',
        'procurement.payment.read',
        'procurement.procurement.read',
        'procurement.read',
        'finance.payments.manage',
        'finance.payment.read',
        'finance.payments.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.vendor_payments.read': [
        'procurement.vendor_payments.read',
        'procurement.vendor-payments.read',
        'procurement.payments.read',
        'procurement.payment.read',
        'procurement.procurement.read',
        'procurement.read',
        'finance.payments.manage',
        'finance.payment.read',
        'finance.payments.read',
        'finance.read',
        'admin.read',
        'super-admin.read',
        'store.read',
        'admin.planthead.read',
        'planthead.read',
      ],
      'procurement.vendor_payments.create': [
        'procurement.vendor_payments.create',
        'procurement.vendor-payments.create',
        'procurement.payments.create',
        'procurement.payment.create',
        'procurement.procurement.create',
        'procurement.create',
        'finance.payments.manage',
        'finance.payment.create',
        'finance.payments.create',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.vendor_payments.update': [
        'procurement.vendor_payments.update',
        'procurement.vendor-payments.update',
        'procurement.payments.update',
        'procurement.payment.update',
        'procurement.procurement.update',
        'procurement.update',
        'finance.payments.manage',
        'finance.payment.update',
        'finance.payments.update',
        'finance.read',
        'admin.read',
        'super-admin.read',
      ],
      'finance.sales-analytics.read': [
        'finance.sales-analytics.read',
        'finance.read',
      ],
      'finance.sales-analytics.export': ['finance.sales-analytics.export'],
      'finance.sales-analytics.activity.read': [
        'finance.sales-analytics.activity.read',
        'finance.sales-analytics.read',
      ],
      'finance.sales-analytics.receivables.read': [
        'finance.sales-analytics.receivables.read',
        'finance.sales-analytics.read',
      ],
      'procurement.procurement.read': [
        'procurement.procurement.read',
        'procurement.indents.read',
        'procurement.po.read',
        'procurement.grn.read',
        'procurement.invoices.read',
        'procurement.payments.read',
        'procurement.read',
        'inventory.stock.read',
        'inventory.inventory.read',
        'finance.read',
        'store.read',
        'admin.read',
        'super-admin.read',
      ],
      'procurement.procurement.create': [
        'procurement.procurement.create',
        'procurement.indents.create',
        'procurement.po.create',
        'procurement.create',
      ],
      'procurement.procurement.reject': [
        'procurement.procurement.reject',
        'procurement.indents.reject',
        'procurement.po.reject',
        'procurement.reject',
      ],
      'sales.salesreports.read': [
        'sales.salesreports.read',
        'sales.reports.read',
        'sales.read',
        'sales.orders.read',
        'sales.leads.read',
        'admin.read',
        'super-admin.read',
        'user.read',
      ],
      'sales.reports.read': [
        'sales.salesreports.read',
        'sales.reports.read',
        'sales.read',
        'sales.orders.read',
        'sales.leads.read',
        'admin.read',
        'super-admin.read',
        'user.read',
      ],
      'hr.departments.read': [
        'hr.departments.read',
        'hr.employees.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'hr.read',
        'user.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.locations.read': [
        'hr.locations.read',
        'hr.employees.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'hr.read',
        'user.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.employees.read': [
        'hr.employees.read',
        'hr.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'employees.read',
        'user.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.attendance.read': [
        'hr.attendance.read',
        'attendance.read',
        'hr.employees.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'hr.read',
        'user.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.requests.create': [
        'hr.recruitment.requests.create',
        'hr.recruitment.create',
        'hr.recruitment.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'recruitment.create',
        'recruitment.read',
        'hr.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.requests.read.all': [
        'hr.recruitment.requests.read.all',
        'hr.recruitment.requests.read.own',
        'hr.recruitment.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'recruitment.read',
        'hr.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.requests.read.own': [
        'hr.recruitment.requests.read.own',
        'hr.recruitment.requests.read.all',
        'hr.recruitment.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'recruitment.read',
        'hr.read',
        'user.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.read': [
        'hr.recruitment.read',
        'hr.recruitment.requests.read.own',
        'hr.recruitment.requests.read.all',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'recruitment.read',
        'hr.read',
        'user.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.requests.update.own': [
        'hr.recruitment.requests.update.own',
        'hr.recruitment.requests.update',
        'hr.recruitment.update',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'hr.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.requests.withdraw': [
        'hr.recruitment.requests.withdraw',
        'hr.recruitment.requests.update.own',
        'hr.recruitment.requests.update',
        'hr.recruitment.update',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'hr.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.recruitment.candidates.create': [
        'hr.recruitment.candidates.create',
        'hr.recruitment.candidates.update',
        'hr.recruitment.create',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'hr.read',
        'admin.read',
        'super-admin.read',
      ],
      'hr.payroll.read': [
        'hr.payroll.read',
        'hr.salary.read',
        'hr.read',
        'admin.read',
        'super-admin.read',
      ],
      'production.reports.read': [
        'production.reports.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.floor.read',
        'production.plan.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
        'user.read',
      ],
      'admin.productionreports.read': [
        'production.reports.read',
        'production.productionworkflow.read',
        'production.workorder.read',
        'production.floor.read',
        'production.plan.read',
        'admin.planthead.read',
        'planthead.read',
        'plant-head.read',
        'admin.read',
        'super-admin.read',
        'user.read',
      ],
    };

    const hasSinglePermission = (reqPerm: string): boolean => {
      const aliases = PERMISSION_ALIASES[reqPerm] || [reqPerm];
      return aliases.some((alias) => allUserPerms.includes(alias));
    };

    const hasPermission = requiredPermissions.some((perm) =>
      hasSinglePermission(perm),
    );

    if (!hasPermission) {
      throw new ForbiddenException('Insufficient permissions');
    }

    return true;
  }
}
