import {
  IsNotEmpty,
  IsNumber,
  IsString,
  IsOptional,
  IsBoolean,
  Min,
  Max,
  IsArray,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';

export class SingleTrackingPointDto {
  @IsNotEmpty()
  @IsNumber()
  @Min(-90)
  @Max(90)
  latitude: number;

  @IsNotEmpty()
  @IsNumber()
  @Min(-180)
  @Max(180)
  longitude: number;

  @IsOptional()
  @IsNumber()
  accuracy?: number | null;

  @IsOptional()
  @IsNumber()
  altitude?: number | null;

  @IsOptional()
  @IsNumber()
  speed?: number | null;

  @IsOptional()
  @IsNumber()
  heading?: number | null;

  @IsOptional()
  @IsNumber()
  batteryLevel?: number | null;

  @IsOptional()
  @IsBoolean()
  isMockLocation?: boolean;

  @IsNotEmpty()
  @IsString()
  clientPointId: string; // Non-null UUID generated by mobile for strict idempotency

  @IsNotEmpty()
  recordedAt: string | Date;

  @IsOptional()
  @IsString()
  source?: string;
}

export class BatchTrackingPointsDto {
  @IsNotEmpty()
  @IsString()
  sessionId: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SingleTrackingPointDto)
  points: SingleTrackingPointDto[];
}
