-- Ensure StockHistoryEvent type exists
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'StockHistoryEvent') THEN
        CREATE TYPE "StockHistoryEvent" AS ENUM (
            'STOCK_IN', 'RESERVE', 'UNRESERVE', 'DISPATCH_OUT', 'QC_RECEIPT', 'ADJUSTMENT', 'RETURN_IN',
            'PRODUCTION_IN', 'PRODUCTION_REVERSAL', 'DISPATCH_REVERSAL', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT',
            'RESERVATION', 'RELEASE'
        );
    END IF;
END $$;

-- AlterEnum
ALTER TYPE "StockHistoryEvent" ADD VALUE IF NOT EXISTS 'PRODUCTION_REVERSAL';
ALTER TYPE "StockHistoryEvent" ADD VALUE IF NOT EXISTS 'DISPATCH_REVERSAL';
