// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/[[...slug]]" | "/dispatch/[[...slug]]" | "/dispatch/returns" | "/employee/payslips" | "/finance-executive/[[...slug]]" | "/finance/[[...slug]]" | "/finance/invoices" | "/finance/ledger" | "/finance/payment-history" | "/finance/payment-verification" | "/finance/payments" | "/finance/purchase-orders" | "/finance/purchase-orders/[id]/close" | "/finance/reports" | "/finance/salary-disbursement" | "/finance/salary-history" | "/finance/salary-verification" | "/finance/salary/history" | "/finance/salary/paid" | "/finance/salary/pending" | "/finance/salary/processing" | "/hr/[[...slug]]" | "/hr/recruitment" | "/hr/roles" | "/hr/salary" | "/hr/salary-structure" | "/hr/salary/history" | "/hr/salary/payslips" | "/hr/salary/prepare" | "/hr/salary/status" | "/login" | "/orders/[orderId]" | "/plant-head/[[...slug]]" | "/plant-head/finished-goods" | "/plant-head/incoming-orders" | "/plant-head/machine-allocation" | "/plant-head/planning" | "/plant-head/product-approval" | "/plant-head/recruitment-request" | "/plant-head/reports" | "/plant-head/work-orders" | "/production/[[...slug]]" | "/production/active" | "/production/completed" | "/production/machine-log" | "/production/reports" | "/production/work-orders" | "/qc/[[...slug]]" | "/sales/[[...slug]]" | "/sales/create-payment" | "/sales/customers" | "/sales/dashboard" | "/sales/leads" | "/sales/leads/[id]/edit" | "/sales/leads/create" | "/sales/orders" | "/sales/payment-followup" | "/sales/payment-history" | "/sales/quotations" | "/sales/quotations/create" | "/sales/reports" | "/sales/samples" | "/store/[[...slug]]" | "/store/reports" | "/store/vendor-master" | "/super-admin/[[...slug]]" | "/super-admin/payroll-analysis" | "/super-admin/po-requests" | "/super-admin/salary-approval" | "/super-admin/salary-approvals"
type AppRouteHandlerRoutes = "/api/backend/auth/login" | "/api/backend/auth/logout" | "/api/backend/auth/refresh" | "/api/backend/customers" | "/api/backend/customers/[id]" | "/api/backend/customers/[id]/deactivate" | "/api/backend/customers/[id]/restore" | "/api/backend/customers/check-duplicates" | "/api/backend/leads" | "/api/backend/leads/[id]" | "/api/backend/leads/[id]/assign-customer" | "/api/backend/leads/[id]/mark-lost" | "/api/backend/leads/[id]/qualify" | "/api/backend/leads/[id]/reminder" | "/api/backend/leads/[id]/reminder/clear" | "/api/backend/leads/[id]/restore" | "/api/backend/leads/[id]/timeline" | "/api/backend/leads/[id]/unassign-customer" | "/api/backend/leads/check-duplicates" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/[...action]" | "/api/production/work-orders" | "/api/qc/pending"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/[[...slug]]": { "slug"?: string[]; }
  "/api/backend/auth/login": {}
  "/api/backend/auth/logout": {}
  "/api/backend/auth/refresh": {}
  "/api/backend/customers": {}
  "/api/backend/customers/[id]": { "id": string; }
  "/api/backend/customers/[id]/deactivate": { "id": string; }
  "/api/backend/customers/[id]/restore": { "id": string; }
  "/api/backend/customers/check-duplicates": {}
  "/api/backend/leads": {}
  "/api/backend/leads/[id]": { "id": string; }
  "/api/backend/leads/[id]/assign-customer": { "id": string; }
  "/api/backend/leads/[id]/mark-lost": { "id": string; }
  "/api/backend/leads/[id]/qualify": { "id": string; }
  "/api/backend/leads/[id]/reminder": { "id": string; }
  "/api/backend/leads/[id]/reminder/clear": { "id": string; }
  "/api/backend/leads/[id]/restore": { "id": string; }
  "/api/backend/leads/[id]/timeline": { "id": string; }
  "/api/backend/leads/[id]/unassign-customer": { "id": string; }
  "/api/backend/leads/check-duplicates": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/[...action]": { "id": string; "action": string[]; }
  "/api/production/work-orders": {}
  "/api/qc/pending": {}
  "/dispatch/[[...slug]]": { "slug"?: string[]; }
  "/dispatch/returns": {}
  "/employee/payslips": {}
  "/finance-executive/[[...slug]]": { "slug"?: string[]; }
  "/finance/[[...slug]]": { "slug"?: string[]; }
  "/finance/invoices": {}
  "/finance/ledger": {}
  "/finance/payment-history": {}
  "/finance/payment-verification": {}
  "/finance/payments": {}
  "/finance/purchase-orders": {}
  "/finance/purchase-orders/[id]/close": { "id": string; }
  "/finance/reports": {}
  "/finance/salary-disbursement": {}
  "/finance/salary-history": {}
  "/finance/salary-verification": {}
  "/finance/salary/history": {}
  "/finance/salary/paid": {}
  "/finance/salary/pending": {}
  "/finance/salary/processing": {}
  "/hr/[[...slug]]": { "slug"?: string[]; }
  "/hr/recruitment": {}
  "/hr/roles": {}
  "/hr/salary": {}
  "/hr/salary-structure": {}
  "/hr/salary/history": {}
  "/hr/salary/payslips": {}
  "/hr/salary/prepare": {}
  "/hr/salary/status": {}
  "/login": {}
  "/orders/[orderId]": { "orderId": string; }
  "/plant-head/[[...slug]]": { "slug"?: string[]; }
  "/plant-head/finished-goods": {}
  "/plant-head/incoming-orders": {}
  "/plant-head/machine-allocation": {}
  "/plant-head/planning": {}
  "/plant-head/product-approval": {}
  "/plant-head/recruitment-request": {}
  "/plant-head/reports": {}
  "/plant-head/work-orders": {}
  "/production/[[...slug]]": { "slug"?: string[]; }
  "/production/active": {}
  "/production/completed": {}
  "/production/machine-log": {}
  "/production/reports": {}
  "/production/work-orders": {}
  "/qc/[[...slug]]": { "slug"?: string[]; }
  "/sales/[[...slug]]": { "slug"?: string[]; }
  "/sales/create-payment": {}
  "/sales/customers": {}
  "/sales/dashboard": {}
  "/sales/leads": {}
  "/sales/leads/[id]/edit": { "id": string; }
  "/sales/leads/create": {}
  "/sales/orders": {}
  "/sales/payment-followup": {}
  "/sales/payment-history": {}
  "/sales/quotations": {}
  "/sales/quotations/create": {}
  "/sales/reports": {}
  "/sales/samples": {}
  "/store/[[...slug]]": { "slug"?: string[]; }
  "/store/reports": {}
  "/store/vendor-master": {}
  "/super-admin/[[...slug]]": { "slug"?: string[]; }
  "/super-admin/payroll-analysis": {}
  "/super-admin/po-requests": {}
  "/super-admin/salary-approval": {}
  "/super-admin/salary-approvals": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
