// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/admin/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admin/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dispatch/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dispatch/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dispatch/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch/returns">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dispatch/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/employee/payslips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/payslips">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/employee/payslips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance-executive/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-executive/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance-executive/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoices">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/ledger/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/ledger">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/ledger/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/payment-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payment-history">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/payment-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/payment-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payment-verification">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/payment-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/payments">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/purchase-orders/[id]/close/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/purchase-orders/[id]/close">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/purchase-orders/[id]/close/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary-disbursement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary-disbursement">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary-disbursement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary-history">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary-verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary-verification">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary-verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary/history">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary/paid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary/paid">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary/paid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary/pending">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/salary/processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/salary/processing">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/salary/processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/recruitment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/recruitment">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/recruitment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/roles">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/salary-structure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary-structure">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/salary-structure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/salary/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary/history">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/salary/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/salary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/salary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/salary/payslips/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary/payslips">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/salary/payslips/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/salary/prepare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary/prepare">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/salary/prepare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/salary/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/salary/status">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/salary/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/orders/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[orderId]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/orders/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/finished-goods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/finished-goods">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/finished-goods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/incoming-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/incoming-orders">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/incoming-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/machine-allocation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/machine-allocation">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/machine-allocation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/planning">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/product-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/product-approval">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/product-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/recruitment-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/recruitment-request">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/recruitment-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/plant-head/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plant-head/work-orders">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/plant-head/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/production/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/production/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/production/active/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/active">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/production/active/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/production/completed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/completed">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/production/completed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/production/machine-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/machine-log">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/production/machine-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/production/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/production/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/production/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production/work-orders">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/production/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/qc/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/qc/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/qc/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/create-payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/create-payment">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/create-payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/customers">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/leads/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/leads/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/leads/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/leads/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/leads/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/leads/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/leads">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/orders">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/payment-followup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/payment-followup">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/payment-followup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/payment-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/payment-history">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/payment-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/quotations/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/quotations/create">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/quotations/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/quotations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/quotations">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/quotations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/sales/samples/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales/samples">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/sales/samples/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/store/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/store/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/store/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/store/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/store/vendor-master/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/vendor-master">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/store/vendor-master/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admin/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admin/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admin/payroll-analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/payroll-analysis">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admin/payroll-analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admin/po-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/po-requests">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admin/po-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admin/salary-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/salary-approval">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admin/salary-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/super-admin/salary-approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/salary-approvals">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/super-admin/salary-approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/backend/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/backend/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/auth/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/backend/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/customers/[id]/deactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/customers/[id]/deactivate">> = Specific
  const handler = {} as typeof import("../../app/api/backend/customers/[id]/deactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/customers/[id]/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/customers/[id]/restore">> = Specific
  const handler = {} as typeof import("../../app/api/backend/customers/[id]/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/customers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/customers/check-duplicates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/customers/check-duplicates">> = Specific
  const handler = {} as typeof import("../../app/api/backend/customers/check-duplicates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/customers">> = Specific
  const handler = {} as typeof import("../../app/api/backend/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/assign-customer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/assign-customer">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/assign-customer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/mark-lost/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/mark-lost">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/mark-lost/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/qualify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/qualify">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/qualify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/reminder/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/reminder/clear">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/reminder/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/reminder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/reminder">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/reminder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/restore">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/timeline">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/[id]/unassign-customer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/[id]/unassign-customer">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/[id]/unassign-customer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/check-duplicates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads/check-duplicates">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/check-duplicates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/backend/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backend/leads">> = Specific
  const handler = {} as typeof import("../../app/api/backend/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/[...action]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/[...action]">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/[...action]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
