-- 1. Add new enum values to ComplaintStatus
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'PLANT_HEAD_PENDING';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'PLANT_HEAD_APPROVED';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'DISPATCH_PENDING';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'DISPATCH_COMPLETED';
ALTER TYPE "ComplaintStatus" ADD VALUE IF NOT EXISTS 'FINANCE_PENDING';
