-- Core procure-to-pay persistence. Prisma schema is the authoritative model.
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "warehouseId" TEXT;
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "requiredDate" TIMESTAMP(3);
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "priority" TEXT DEFAULT 'NORMAL';
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "businessReason" TEXT;
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "remarks" TEXT;
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "cancellationReason" TEXT;
ALTER TABLE "PurchaseIndent" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PurchaseIndentItem" ADD COLUMN IF NOT EXISTS "approvedQuantity" DECIMAL(14,2);
ALTER TABLE "PurchaseIndentItem" ADD COLUMN IF NOT EXISTS "estimatedUnitRate" DECIMAL(14,2);
ALTER TABLE "PurchaseIndentItem" ADD COLUMN IF NOT EXISTS "lineRemarks" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "purchaseIndentId" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'DRAFT';
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "poNumber" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "freight" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "otherCharges" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "paymentTerms" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "expectedDeliveryDate" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "issuedAt" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "issuedById" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "snapshot" JSONB;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "discountPercent" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "gstPercent" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "receivedQuantity" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "acceptedQuantity" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "grnNumber" TEXT;
ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "receivedById" TEXT;
ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "snapshot" JSONB;
ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "inventoryPostedAt" TIMESTAMP(3);
ALTER TABLE "GoodsReceiptNoteItem" ADD COLUMN IF NOT EXISTS "receivedQuantity" DECIMAL(14,2) NOT NULL DEFAULT 0;
ALTER TABLE "GoodsReceiptNoteItem" ADD COLUMN IF NOT EXISTS "inspectionRemarks" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "PurchaseOrder_purchaseIndentId_key" ON "PurchaseOrder"("purchaseIndentId");
CREATE UNIQUE INDEX IF NOT EXISTS "PurchaseOrder_poNumber_key" ON "PurchaseOrder"("poNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "GoodsReceiptNote_grnNumber_key" ON "GoodsReceiptNote"("grnNumber");
CREATE INDEX IF NOT EXISTS "PurchaseIndent_status_idx" ON "PurchaseIndent"("status");
CREATE INDEX IF NOT EXISTS "PurchaseOrder_status_idx" ON "PurchaseOrder"("status");
CREATE INDEX IF NOT EXISTS "GoodsReceiptNote_status_idx" ON "GoodsReceiptNote"("status");
