const rawInput = `HIMALAYA FRP MHC 10X10 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 LD WHITE 	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 10X10 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 12X12 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 15X15 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 18X18 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 18X24 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 21X21 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 24X24 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 ELD BLACJK	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 LD BLACJK	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 28X28 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 30X30 LD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 ELD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 LD WHITE	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 ELD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 LD RED	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 ELD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 LD GRAY	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 ELD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 LD BLACK	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 ELD GREEN	HIMALAYA	MFG
HIMALAYA FRP MHC 36X36 LD GREEN	HIMALAYA	MFG`;

function parseProducts() {
  const lines = rawInput.split('\n').map(l => l.trim()).filter(Boolean);
  console.log('Total lines found:', lines.length);

  const items = [];
  for (const line of lines) {
    const parts = line.split('\t').map(p => p.trim()).filter(Boolean);
    let rawName = parts[0] || line;
    
    // Normalize spaces and fix typo BLACJK -> BLACK
    let cleanName = rawName.replace(/\s+/g, ' ').replace(/\bBLACJK\b/g, 'BLACK');
    
    // Parse size, load, color from cleanName
    // e.g. "HIMALAYA FRP MHC 10X10 ELD WHITE"
    const match = cleanName.match(/HIMALAYA\s+FRP\s+MHC\s+([0-9]+X[0-9]+)\s+(ELD|LD)\s+([A-Z]+)/i);
    if (!match) {
      console.warn('Could not regex match:', cleanName);
      continue;
    }

    const size = match[1].toUpperCase();
    const capacity = match[2].toUpperCase();
    const color = match[3].toUpperCase();
    const sku = cleanName.replace(/[^a-zA-Z0-9]/g, '').toUpperCase().substring(0, 50);

    items.push({
      name: cleanName,
      sku: sku,
      brand: 'HIMALAYA',
      category: 'FRP COVERS',
      productType: 'MANUFACTURING',
      dispatchCategory: 'D1',
      unit: 'SET',
      unitPrice: 0,
      gstRate: 18,
      hsnCode: '39259090',
      size: size,
      type: 'MHC',
      capacity: capacity,
      variantDetails: `MHC ${size} ${capacity} ${color}`,
      description: cleanName,
      coversPerSet: 1,
      framesPerSet: 1,
      minimumStock: 0,
      isActive: true
    });
  }

  return items;
}

const parsed = parseProducts();
console.log(`Successfully parsed ${parsed.length} items.`);
if (parsed.length > 0) {
  console.log('Sample parsed item:', JSON.stringify(parsed[0], null, 2));
  console.log('Last parsed item:', JSON.stringify(parsed[parsed.length - 1], null, 2));
}

module.exports = { parsed };
