import { useState, useEffect } from 'react';
import Swal from 'sweetalert2';
import { 
  FileText, 
  Download, 
  Send, 
  Clock, 
  Search, 
  CheckCircle2,
  AlertTriangle,
  RefreshCw
} from 'lucide-react';
import { apiClient } from '../../../lib/apiClient';
import StatusBadge from '../../../shared/components/StatusBadge';

export default function InvoicesView() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const [showTimeline, setShowTimeline] = useState(false);

  const fetchInvoices = async () => {
    setLoading(true);
    try {
      const res = await apiClient.get('/v1/billing/invoices');
      if (res.success) {
        setInvoices(res.data);
      }
    } catch (err) {
      console.error('Error fetching invoices:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInvoices();
  }, []);

  const handleDownloadPDF = (inv) => {
    Swal.fire({
      title: 'Generating PDF Invoice...',
      html: 'Rendering document layout and signature seals.',
      timer: 1500,
      timerProgressBar: true,
      didOpen: () => {
        Swal.showLoading();
      }
    }).then(() => {
      Swal.fire({
        icon: 'success',
        title: 'Downloaded!',
        text: `Invoice ${inv.invoice_number} PDF downloaded successfully.`,
        timer: 1500,
        showConfirmButton: false
      });
    });
  };

  const handleSendReminder = async (inv) => {
    const confirm = await Swal.fire({
      title: 'Send Payment Reminder?',
      text: `Send an automated WhatsApp and Email payment reminder to ${inv.customer_name} for the outstanding balance of ${formatCurrency(inv.balance_amount)}?`,
      icon: 'question',
      showCancelButton: true,
      confirmButtonText: 'Yes, Send',
      cancelButtonText: 'Cancel',
      confirmButtonColor: '#337a86'
    });

    if (confirm.isConfirmed) {
      Swal.fire({
        icon: 'success',
        title: 'Reminder Sent!',
        text: `Reminder dispatched to ${inv.customer_name}.`,
        timer: 2000,
        showConfirmButton: false
      });
    }
  };

  const formatCurrency = (val) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR'
    }).format(val);
  };

  const openTimeline = (inv) => {
    setSelectedInvoice(inv);
    setShowTimeline(true);
  };

  // Aggregated status metrics
  const invoiceStats = invoices.reduce((acc, inv) => {
    const amt = parseFloat(inv.total_amount) || 0;
    acc.totalVal += amt;
    if (inv.invoice_status === 'Paid') acc.paid += amt;
    else if (inv.invoice_status === 'Partially Paid') acc.partial += amt;
    else if (inv.invoice_status === 'Overdue') acc.overdue += amt;
    else if (inv.invoice_status === 'Cancelled') acc.cancelled += amt;
    return acc;
  }, { totalVal: 0, paid: 0, partial: 0, overdue: 0, cancelled: 0 });

  const filteredInvoices = invoices.filter(inv => 
    inv.invoice_number?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    inv.customer_name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
    inv.order_number?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ fontSize: '22px', fontWeight: '800', color: 'var(--color-text-primary)', letterSpacing: '-0.5px' }}>Billing Invoices Register</h1>
          <p style={{ color: 'var(--color-text-secondary)', fontSize: '13px', marginTop: '4px' }}>Access and manage all customer sales invoices generated by the Billing module.</p>
        </div>
        <button 
          onClick={fetchInvoices} 
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '38px',
            height: '38px',
            background: 'var(--color-sidebar-bg)',
            border: '1px solid var(--color-border)',
            borderRadius: '10px',
            cursor: 'pointer',
            boxShadow: 'var(--shadow-card)',
            color: 'var(--color-text-primary)'
          }}
        >
          <RefreshCw size={16} />
        </button>
      </div>

      {/* KPI Cards Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '20px' }}>
        <div className="app-card border-left-blue">
          <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontWeight: '600', uppercase: 'true' }}>Total Invoice Value</span>
          <h3 style={{ margin: '6px 0 2px 0', fontSize: '20px', fontWeight: '800' }}>{formatCurrency(invoiceStats.totalVal)}</h3>
        </div>
        <div className="app-card border-left-emerald">
          <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontWeight: '600', uppercase: 'true', color: '#10b981' }}>Paid Invoices</span>
          <h3 style={{ margin: '6px 0 2px 0', fontSize: '20px', fontWeight: '800', color: '#10b981' }}>{formatCurrency(invoiceStats.paid)}</h3>
        </div>
        <div className="app-card border-left-blue">
          <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontWeight: '600', uppercase: 'true', color: 'var(--color-accent-teal)' }}>Partially Paid</span>
          <h3 style={{ margin: '6px 0 2px 0', fontSize: '20px', fontWeight: '800', color: 'var(--color-accent-teal)' }}>{formatCurrency(invoiceStats.partial)}</h3>
        </div>
        <div className="app-card border-left-red">
          <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontWeight: '600', uppercase: 'true', color: '#ef4444' }}>Overdue Amount</span>
          <h3 style={{ margin: '6px 0 2px 0', fontSize: '20px', fontWeight: '800', color: '#ef4444' }}>{formatCurrency(invoiceStats.overdue)}</h3>
        </div>
        <div className="app-card border-left-amber">
          <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontWeight: '600', uppercase: 'true', color: '#5E6B82' }}>Cancelled</span>
          <h3 style={{ margin: '6px 0 2px 0', fontSize: '20px', fontWeight: '800', color: '#5E6B82' }}>{formatCurrency(invoiceStats.cancelled)}</h3>
        </div>
      </div>

      {/* Search and Filters */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', padding: '12px 16px', background: '#F5FAFE', borderRadius: '12px', border: '1px solid var(--color-border)' }}>
        <div style={{ position: 'relative', width: '280px' }}>
          <input
            type="text"
            placeholder="Search by invoice, customer, order..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{
              width: '100%',
              padding: '8px 12px 8px 32px',
              background: '#ffffff',
              border: '1px solid var(--color-border)',
              borderRadius: '10px',
              fontSize: '12px',
              color: 'var(--color-text-primary)'
            }}
          />
          <span style={{ position: 'absolute', left: '10px', top: '50%', transform: 'translateY(-50%)', color: 'var(--color-text-secondary)', display: 'flex', alignItems: 'center' }}>
            <Search size={14} />
          </span>
        </div>
      </div>

      {/* Invoices Table */}
      <div className="app-card" style={{ padding: '20px' }}>
        {loading ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', gap: '12px' }}>
            <div className="animate-spin" style={{ width: '28px', height: '28px', border: '3px solid var(--color-accent-teal)', borderBottomColor: 'transparent', borderRadius: '50%' }}></div>
            <p style={{ color: 'var(--color-text-secondary)', fontSize: '12px' }}>Loading invoices...</p>
          </div>
        ) : (
          <div className="crm-table-container">
            <table className="crm-table responsive-table">
              <thead>
                <tr>
                  <th>Invoice No</th>
                  <th>Customer</th>
                  <th>Order Ref</th>
                  <th>Invoice Date</th>
                  <th>Due Date</th>
                  <th>Amount</th>
                  <th>Paid</th>
                  <th>Balance</th>
                  <th style={{ textAlign: 'center' }}>Status</th>
                  <th style={{ textAlign: 'right' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {filteredInvoices.length === 0 ? (
                  <tr>
                    <td colSpan="10" style={{ textAlign: 'center', color: 'var(--color-text-muted)', padding: '30px' }}>
                      No invoices found.
                    </td>
                  </tr>
                ) : (
                  filteredInvoices.map((inv) => (
                    <tr key={inv.invoice_id}>
                      <td data-label="Invoice No" style={{ fontWeight: 'bold' }}>{inv.invoice_number}</td>
                      <td data-label="Customer" style={{ fontWeight: 'bold' }}>{inv.customer_name}</td>
                      <td data-label="Order Ref" style={{ fontFamily: 'monospace' }}>{inv.order_number}</td>
                      <td data-label="Invoice Date">{new Date(inv.generated_at).toLocaleDateString()}</td>
                      <td data-label="Due Date">{new Date(inv.due_date).toLocaleDateString()}</td>
                      <td data-label="Amount" style={{ fontWeight: 'bold' }}>{formatCurrency(inv.total_amount)}</td>
                      <td data-label="Paid" style={{ color: '#10b981', fontWeight: 'bold' }}>{formatCurrency(inv.paid_amount)}</td>
                      <td data-label="Balance" style={{ color: '#ef4444', fontWeight: 'bold' }}>{formatCurrency(inv.balance_amount)}</td>
                      <td data-label="Status" style={{ textAlign: 'center' }}>
                        <StatusBadge status={inv.invoice_status} />
                      </td>
                      <td data-label="Action" style={{ textAlign: 'right' }}>
                        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px' }}>
                          <button
                            onClick={() => openTimeline(inv)}
                            style={{
                              padding: '6px',
                              background: 'var(--color-sidebar-bg)',
                              border: '1px solid var(--color-border)',
                              borderRadius: '6px',
                              cursor: 'pointer',
                              color: 'var(--color-accent-teal)',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center'
                            }}
                            title="View Timeline"
                          >
                            <Clock size={14} />
                          </button>
                          <button
                            onClick={() => handleDownloadPDF(inv)}
                            style={{
                              padding: '6px',
                              background: 'var(--color-sidebar-bg)',
                              border: '1px solid var(--color-border)',
                              borderRadius: '6px',
                              cursor: 'pointer',
                              color: 'var(--color-text-secondary)',
                              display: 'flex',
                              alignItems: 'center',
                              justifyContent: 'center'
                            }}
                            title="Download PDF"
                          >
                            <Download size={14} />
                          </button>
                          {parseFloat(inv.balance_amount) > 0 && (
                            <button
                              onClick={() => handleSendReminder(inv)}
                              style={{
                                padding: '6px',
                                background: 'var(--color-sidebar-bg)',
                                border: '1px solid var(--color-border)',
                                borderRadius: '6px',
                                cursor: 'pointer',
                                color: '#f59e0b',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center'
                              }}
                              title="Send Payment Reminder"
                            >
                              <Send size={14} />
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Timeline Modal */}
      {showTimeline && selectedInvoice && (
        <div style={{
          position: 'fixed',
          inset: 0,
          background: 'rgba(0,0,0,0.5)',
          backdropFilter: 'blur(4px)',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          padding: '16px',
          zIndex: 9999
        }}>
          <div className="app-card" style={{ maxWidth: '450px', width: '100%', padding: '0', overflow: 'hidden' }}>
            <div style={{ padding: '16px 24px', borderBottom: '1px solid var(--color-border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#F5FAFE' }}>
              <div>
                <h3 style={{ margin: 0, fontSize: '15px', fontWeight: '800' }}>Invoice Timeline</h3>
                <p style={{ margin: '2px 0 0 0', fontSize: '11px', color: 'var(--color-text-secondary)' }}>{selectedInvoice.invoice_number} - {selectedInvoice.customer_name}</p>
              </div>
              <button 
                onClick={() => setShowTimeline(false)} 
                style={{ background: 'transparent', border: 'none', fontSize: '20px', cursor: 'pointer', color: 'var(--color-text-secondary)' }}
              >
                &times;
              </button>
            </div>
            <div style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
              {/* Vertical Timeline */}
              <div style={{ position: 'relative', borderLeft: '2px solid var(--color-border)', marginLeft: '12px', paddingLeft: '24px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
                {/* Step 1: Created */}
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '-31px', top: '2px', background: '#10b981', color: '#fff', borderRadius: '50%', width: '14px', height: '14px', border: '2px solid #fff', display: 'block' }}></span>
                  <h4 style={{ margin: 0, fontSize: '13px', fontWeight: '700' }}>Invoice Generated</h4>
                  <p style={{ margin: '4px 0 0 0', fontSize: '11px', color: 'var(--color-text-secondary)' }}>Bill generated for {formatCurrency(selectedInvoice.total_amount)}.</p>
                  <p style={{ margin: '4px 0 0 0', fontSize: '10px', color: 'var(--color-text-muted)' }}>{new Date(selectedInvoice.generated_at).toLocaleString()}</p>
                </div>

                {/* Step 2: Payment Recorded */}
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '-31px', top: '2px', background: parseFloat(selectedInvoice.paid_amount) > 0 ? '#10b981' : '#D6E2F0', color: '#fff', borderRadius: '50%', width: '14px', height: '14px', border: '2px solid #fff', display: 'block' }}></span>
                  <h4 style={{ margin: 0, fontSize: '13px', fontWeight: '700' }}>Payment Received</h4>
                  <p style={{ margin: '4px 0 0 0', fontSize: '11px', color: 'var(--color-text-secondary)' }}>
                    {parseFloat(selectedInvoice.paid_amount) > 0 
                      ? `Paid: ${formatCurrency(selectedInvoice.paid_amount)}` 
                      : 'No payments verified yet.'}
                  </p>
                </div>

                {/* Step 3: Status */}
                <div style={{ position: 'relative' }}>
                  <span style={{ position: 'absolute', left: '-31px', top: '2px', background: selectedInvoice.invoice_status === 'Paid' ? '#10b981' : '#f59e0b', color: '#fff', borderRadius: '50%', width: '14px', height: '14px', border: '2px solid #fff', display: 'block' }}></span>
                  <h4 style={{ margin: 0, fontSize: '13px', fontWeight: '700' }}>Settlement Status</h4>
                  <p style={{ margin: '4px 0 0 0', fontSize: '11px', color: 'var(--color-text-secondary)' }}>Invoice status is currently: <strong>{selectedInvoice.invoice_status}</strong>.</p>
                  {parseFloat(selectedInvoice.balance_amount) > 0 && (
                    <p style={{ margin: '4px 0 0 0', fontSize: '11px', color: '#ef4444', fontWeight: '700' }}>Pending Balance: {formatCurrency(selectedInvoice.balance_amount)}</p>
                  )}
                </div>
              </div>
            </div>
            <div style={{ padding: '12px 24px', borderTop: '1px solid var(--color-border)', display: 'flex', justifyContent: 'flex-end', background: '#F5FAFE' }}>
              <button 
                onClick={() => setShowTimeline(false)}
                style={{
                  padding: '6px 16px',
                  background: 'var(--color-accent-teal)',
                  color: '#fff',
                  border: 'none',
                  borderRadius: '6px',
                  fontWeight: '700',
                  fontSize: '12px',
                  cursor: 'pointer'
                }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
