-- AlterEnum
ALTER TYPE "StockHistoryEvent" ADD VALUE IF NOT EXISTS 'EXTRA_COVER_IN';
ALTER TYPE "StockHistoryEvent" ADD VALUE IF NOT EXISTS 'EXTRA_FRAME_IN';
ALTER TYPE "StockHistoryEvent" ADD VALUE IF NOT EXISTS 'EXTRA_COVER_REVERSAL';
ALTER TYPE "StockHistoryEvent" ADD VALUE IF NOT EXISTS 'EXTRA_FRAME_REVERSAL';
